package bls12377

import (
	"crypto/rand"
	"math/big"

	"github.com/consensys/gnark-crypto/ecc"
	curve "github.com/consensys/gnark-crypto/ecc/bls12-377"
	"github.com/consensys/gnark-crypto/ecc/bls12-377/fp"
	"github.com/consensys/gnark-crypto/ecc/bls12-377/fr"
)

// IsInSubGroupBatchNaive checks if a batch of points P_i are in G1.
// This is a naive method that checks each point individually using Scott test
// [Scott21].
//
// [Scott21]: https://eprint.iacr.org/2021/1130.pdf
func IsInSubGroupBatchNaive(points []curve.G1Affine) bool {
	for i := range points {
		if !points[i].IsInSubGroup() {
			return false
		}
	}
	return true
}

// IsInSubGroupBatch checks if a batch of points P_i are in G1.
// First, it checks that all points are on a larger torsion E[r*e'] using Tate
// pairings [Koshelev22].
// Second, it generates random scalars s_i in the range [0, bound), performs
// n=rounds multi-scalar-multiplication Sj=∑[s_i]P_i of sizes N=len(points) and
// checks if Sj are on E[r] using Scott test [Scott21].
//
// [Koshelev22]: https://eprint.iacr.org/2022/037.pdf
// [Scott21]: https://eprint.iacr.org/2021/1130.pdf
func IsInSubGroupBatch(points []curve.G1Affine, bound *big.Int, rounds int) bool {

	// 1. Check points are on E[r*e']
	for i := range points {
		// 1.1. Tate_{2^4,P16}(Q) == 1
		if !isFirstTateOne(points[i]) {
			return false
		}
		// 1.2. Tate_{3,P3}(Q) == 1
		if !isSecondTateOne(points[i]) {
			return false
		}
		// 1.3. Tate_{7,P7}(Q) == 1
		if !isThirdTateOne(points[i]) {
			return false
		}
		// 1.4. Tate_{11,P11}(Q) == 1
		if !isFourthTateOne(points[i]) {
			return false
		}
	}

	// 2. Check Sj are on E[r]
	for i := 0; i < rounds; i++ {
		b, err := rand.Int(rand.Reader, bound)
		if err != nil {
			panic(err)
		}
		randoms := make([]fr.Element, len(points))
		for j := range randoms {
			randoms[j].SetBigInt(b)
		}
		var sum curve.G1Jac
		sum.MultiExp(points[:], randoms[:], ecc.MultiExpConfig{})
		if !sum.IsInSubGroup() {
			return false
		}
	}
	return true
}

func isFirstTateOne(point curve.G1Affine) bool {
	return true
}

// isSecondTateOne checks that Tate_{3,P3}(Q) = (y-1)^((p-1)/3) == 1
// where P3 = (0,1) a point of order 3 on the curve.
func isSecondTateOne(point curve.G1Affine) bool {
	var tate, one fp.Element
	one.SetOne()
	tate.Sub(&point.Y, &one)
	tate = *expByp3(&tate)
	return tate.IsOne()
}

func isThirdTateOne(point curve.G1Affine) bool {
	return true
}

func isFourthTateOne(point curve.G1Affine) bool {
	return true
}

// --------------------

// line represents a line in the form y + ax + b = 0.
//
// A a line through P=(x1,y1) and Q=(x2,y2) has:
//
//	a = (y1 - y2) / (x2 - x1)
//	b = -y1 - a*x1
//
// A tangent line to P=(x1,y1) has:
//
//	a = -3*x1^2 / (2*y1)
//	b = -y1 - a*x1
//
// A vertical line through P=(x1,y1) has::
//
// a = 0
// b = -x1
type line struct {
	a, b fp.Element
}

var lines16 [7]line

func init() {
	// P = (
	// 	   0x62af02c766f6bdd9a611da0db5cbd52102751f8476d97903a05a3274fb0b498d99628c38327d58081e1e8107930a64,
	// 	   0x17ffe960fa1502725f36844f63a83638e2a7e321948984a95ba562cf719f6785139614a1c1de0d2da5211384f762bd4,
	// ) of order 16
	//
	// l_{P,P}
	lines16[0].a.SetString("186753577267350681523223042672752493139503988550545545075290854342660310908569018683427166604708127195493070987924")
	lines16[0].b.SetString("107330485521934419149968690552530385427291718866313009555984104959818466429125580230768172226069235556223352865086")
	// l_{2P,2P}
	lines16[1].a.SetString("")
	lines16[1].b.SetString("")
	// l_{4P,4P}
	lines16[2].a.SetString("")
	lines16[2].b.SetString("")
	// v_P
	lines16[3].b.SetString("")
	// v_{2P}
	lines16[4].b.SetString("")
	// v_{4P}
	lines16[5].b.SetString("")
	// v_{8P}
	lines16[6].b.SetString("")
}

// expByp3 uses a short addition chain to compute x^p3 where p3=(p-1)/3 .
func expByp3(x *fp.Element) *fp.Element {
	// Operations: 370 squares 62 multiplies
	//
	// Generated by github.com/mmcloughlin/addchain v0.4.0.

	// Allocate Temporaries.
	var z = new(fp.Element)
	var (
		t0  = new(fp.Element)
		t1  = new(fp.Element)
		t2  = new(fp.Element)
		t3  = new(fp.Element)
		t4  = new(fp.Element)
		t5  = new(fp.Element)
		t6  = new(fp.Element)
		t7  = new(fp.Element)
		t8  = new(fp.Element)
		t9  = new(fp.Element)
		t10 = new(fp.Element)
		t11 = new(fp.Element)
		t12 = new(fp.Element)
		t13 = new(fp.Element)
		t14 = new(fp.Element)
		t15 = new(fp.Element)
		t16 = new(fp.Element)
		t17 = new(fp.Element)
	)

	// Step 1: t15 = x^0x2
	t15.Square(x)

	// Step 2: t11 = x^0x3
	t11.Mul(x, t15)

	// Step 3: t2 = x^0x4
	t2.Mul(x, t11)

	// Step 4: t8 = x^0x5
	t8.Mul(x, t2)

	// Step 5: t3 = x^0x6
	t3.Mul(x, t8)

	// Step 6: t12 = x^0x9
	t12.Mul(t11, t3)

	// Step 7: z = x^0xb
	z.Mul(t15, t12)

	// Step 8: t0 = x^0xc
	t0.Mul(x, z)

	// Step 9: t1 = x^0xd
	t1.Mul(x, t0)

	// Step 10: t5 = x^0xf
	t5.Mul(t15, t1)

	// Step 11: t0 = x^0x1b
	t0.Mul(t0, t5)

	// Step 12: t13 = x^0x1d
	t13.Mul(t15, t0)

	// Step 13: t16 = x^0x23
	t16.Mul(t3, t13)

	// Step 14: t7 = x^0x25
	t7.Mul(t15, t16)

	// Step 15: t6 = x^0x29
	t6.Mul(t2, t7)

	// Step 16: t14 = x^0x2f
	t14.Mul(t3, t6)

	// Step 17: t4 = x^0x31
	t4.Mul(t15, t14)

	// Step 18: t9 = x^0x35
	t9.Mul(t2, t4)

	// Step 19: t2 = x^0x39
	t2.Mul(t2, t9)

	// Step 20: t10 = x^0x3b
	t10.Mul(t15, t2)

	// Step 21: t3 = x^0x3d
	t3.Mul(t15, t10)

	// Step 22: t17 = x^0x46
	t17.Mul(t12, t3)

	// Step 26: t17 = x^0x460
	for s := 0; s < 4; s++ {
		t17.Square(t17)
	}

	// Step 27: t17 = x^0x47b
	t17.Mul(t0, t17)

	// Step 34: t17 = x^0x23d80
	for s := 0; s < 7; s++ {
		t17.Square(t17)
	}

	// Step 35: t16 = x^0x23da3
	t16.Mul(t16, t17)

	// Step 40: t16 = x^0x47b460
	for s := 0; s < 5; s++ {
		t16.Square(t16)
	}

	// Step 41: t16 = x^0x47b461
	t16.Mul(x, t16)

	// Step 53: t16 = x^0x47b461000
	for s := 0; s < 12; s++ {
		t16.Square(t16)
	}

	// Step 54: t15 = x^0x47b461002
	t15.Mul(t15, t16)

	// Step 55: t15 = x^0x47b46103f
	t15.Mul(t3, t15)

	// Step 62: t15 = x^0x23da3081f80
	for s := 0; s < 7; s++ {
		t15.Square(t15)
	}

	// Step 63: t15 = x^0x23da3081fb1
	t15.Mul(t4, t15)

	// Step 70: t15 = x^0x11ed1840fd880
	for s := 0; s < 7; s++ {
		t15.Square(t15)
	}

	// Step 71: t15 = x^0x11ed1840fd8b5
	t15.Mul(t9, t15)

	// Step 75: t15 = x^0x11ed1840fd8b50
	for s := 0; s < 4; s++ {
		t15.Square(t15)
	}

	// Step 76: t15 = x^0x11ed1840fd8b5f
	t15.Mul(t5, t15)

	// Step 85: t15 = x^0x23da3081fb16be00
	for s := 0; s < 9; s++ {
		t15.Square(t15)
	}

	// Step 86: t15 = x^0x23da3081fb16be3b
	t15.Mul(t10, t15)

	// Step 94: t15 = x^0x23da3081fb16be3b00
	for s := 0; s < 8; s++ {
		t15.Square(t15)
	}

	// Step 95: t14 = x^0x23da3081fb16be3b2f
	t14.Mul(t14, t15)

	// Step 101: t14 = x^0x8f68c207ec5af8ecbc0
	for s := 0; s < 6; s++ {
		t14.Square(t14)
	}

	// Step 102: t14 = x^0x8f68c207ec5af8ecbe5
	t14.Mul(t7, t14)

	// Step 108: t14 = x^0x23da3081fb16be3b2f940
	for s := 0; s < 6; s++ {
		t14.Square(t14)
	}

	// Step 109: t13 = x^0x23da3081fb16be3b2f95d
	t13.Mul(t13, t14)

	// Step 121: t13 = x^0x23da3081fb16be3b2f95d000
	for s := 0; s < 12; s++ {
		t13.Square(t13)
	}

	// Step 122: t12 = x^0x23da3081fb16be3b2f95d009
	t12.Mul(t12, t13)

	// Step 132: t12 = x^0x8f68c207ec5af8ecbe57402400
	for s := 0; s < 10; s++ {
		t12.Square(t12)
	}

	// Step 133: t12 = x^0x8f68c207ec5af8ecbe57402435
	t12.Mul(t9, t12)

	// Step 135: t12 = x^0x23da3081fb16be3b2f95d0090d4
	for s := 0; s < 2; s++ {
		t12.Square(t12)
	}

	// Step 136: t11 = x^0x23da3081fb16be3b2f95d0090d7
	t11.Mul(t11, t12)

	// Step 146: t11 = x^0x8f68c207ec5af8ecbe57402435c00
	for s := 0; s < 10; s++ {
		t11.Square(t11)
	}

	// Step 147: t11 = x^0x8f68c207ec5af8ecbe57402435c31
	t11.Mul(t4, t11)

	// Step 155: t11 = x^0x8f68c207ec5af8ecbe57402435c3100
	for s := 0; s < 8; s++ {
		t11.Square(t11)
	}

	// Step 156: t10 = x^0x8f68c207ec5af8ecbe57402435c313b
	t10.Mul(t10, t11)

	// Step 163: t10 = x^0x47b46103f62d7c765f2ba0121ae189d80
	for s := 0; s < 7; s++ {
		t10.Square(t10)
	}

	// Step 164: t10 = x^0x47b46103f62d7c765f2ba0121ae189d9b
	t10.Mul(t0, t10)

	// Step 173: t10 = x^0x8f68c207ec5af8ecbe57402435c313b3600
	for s := 0; s < 9; s++ {
		t10.Square(t10)
	}

	// Step 174: t10 = x^0x8f68c207ec5af8ecbe57402435c313b360f
	t10.Mul(t5, t10)

	// Step 182: t10 = x^0x8f68c207ec5af8ecbe57402435c313b360f00
	for s := 0; s < 8; s++ {
		t10.Square(t10)
	}

	// Step 183: t9 = x^0x8f68c207ec5af8ecbe57402435c313b360f35
	t9.Mul(t9, t10)

	// Step 187: t9 = x^0x8f68c207ec5af8ecbe57402435c313b360f350
	for s := 0; s < 4; s++ {
		t9.Square(t9)
	}

	// Step 188: t9 = x^0x8f68c207ec5af8ecbe57402435c313b360f351
	t9.Mul(x, t9)

	// Step 200: t9 = x^0x8f68c207ec5af8ecbe57402435c313b360f351000
	for s := 0; s < 12; s++ {
		t9.Square(t9)
	}

	// Step 201: t8 = x^0x8f68c207ec5af8ecbe57402435c313b360f351005
	t8.Mul(t8, t9)

	// Step 209: t8 = x^0x8f68c207ec5af8ecbe57402435c313b360f35100500
	for s := 0; s < 8; s++ {
		t8.Square(t8)
	}

	// Step 210: t8 = x^0x8f68c207ec5af8ecbe57402435c313b360f3510051b
	t8.Mul(t0, t8)

	// Step 219: t8 = x^0x11ed1840fd8b5f1d97cae80486b862766c1e6a200a3600
	for s := 0; s < 9; s++ {
		t8.Square(t8)
	}

	// Step 220: t7 = x^0x11ed1840fd8b5f1d97cae80486b862766c1e6a200a3625
	t7.Mul(t7, t8)

	// Step 226: t7 = x^0x47b46103f62d7c765f2ba0121ae189d9b079a88028d8940
	for s := 0; s < 6; s++ {
		t7.Square(t7)
	}

	// Step 227: t7 = x^0x47b46103f62d7c765f2ba0121ae189d9b079a88028d897d
	t7.Mul(t3, t7)

	// Step 233: t7 = x^0x11ed1840fd8b5f1d97cae80486b862766c1e6a200a3625f40
	for s := 0; s < 6; s++ {
		t7.Square(t7)
	}

	// Step 234: t7 = x^0x11ed1840fd8b5f1d97cae80486b862766c1e6a200a3625f69
	t7.Mul(t6, t7)

	// Step 240: t7 = x^0x47b46103f62d7c765f2ba0121ae189d9b079a88028d897da40
	for s := 0; s < 6; s++ {
		t7.Square(t7)
	}

	// Step 241: t7 = x^0x47b46103f62d7c765f2ba0121ae189d9b079a88028d897da7d
	t7.Mul(t3, t7)

	// Step 247: t7 = x^0x11ed1840fd8b5f1d97cae80486b862766c1e6a200a3625f69f40
	for s := 0; s < 6; s++ {
		t7.Square(t7)
	}

	// Step 248: t7 = x^0x11ed1840fd8b5f1d97cae80486b862766c1e6a200a3625f69f79
	t7.Mul(t2, t7)

	// Step 254: t7 = x^0x47b46103f62d7c765f2ba0121ae189d9b079a88028d897da7de40
	for s := 0; s < 6; s++ {
		t7.Square(t7)
	}

	// Step 255: t7 = x^0x47b46103f62d7c765f2ba0121ae189d9b079a88028d897da7de5b
	t7.Mul(t0, t7)

	// Step 263: t7 = x^0x47b46103f62d7c765f2ba0121ae189d9b079a88028d897da7de5b00
	for s := 0; s < 8; s++ {
		t7.Square(t7)
	}

	// Step 264: t6 = x^0x47b46103f62d7c765f2ba0121ae189d9b079a88028d897da7de5b29
	t6.Mul(t6, t7)

	// Step 268: t6 = x^0x47b46103f62d7c765f2ba0121ae189d9b079a88028d897da7de5b290
	for s := 0; s < 4; s++ {
		t6.Square(t6)
	}

	// Step 269: t5 = x^0x47b46103f62d7c765f2ba0121ae189d9b079a88028d897da7de5b29f
	t5.Mul(t5, t6)

	// Step 282: t5 = x^0x8f68c207ec5af8ecbe57402435c313b360f3510051b12fb4fbcb653e000
	for s := 0; s < 13; s++ {
		t5.Square(t5)
	}

	// Step 283: t4 = x^0x8f68c207ec5af8ecbe57402435c313b360f3510051b12fb4fbcb653e031
	t4.Mul(t4, t5)

	// Step 284: t4 = x^0x11ed1840fd8b5f1d97cae80486b862766c1e6a200a3625f69f796ca7c062
	t4.Square(t4)

	// Step 285: t4 = x^0x11ed1840fd8b5f1d97cae80486b862766c1e6a200a3625f69f796ca7c063
	t4.Mul(x, t4)

	// Step 307: t4 = x^0x47b46103f62d7c765f2ba0121ae189d9b079a88028d897da7de5b29f018c00000
	for s := 0; s < 22; s++ {
		t4.Square(t4)
	}

	// Step 308: t3 = x^0x47b46103f62d7c765f2ba0121ae189d9b079a88028d897da7de5b29f018c0003d
	t3.Mul(t3, t4)

	// Step 315: t3 = x^0x23da3081fb16be3b2f95d0090d70c4ecd83cd440146c4bed3ef2d94f80c60001e80
	for s := 0; s < 7; s++ {
		t3.Square(t3)
	}

	// Step 316: t2 = x^0x23da3081fb16be3b2f95d0090d70c4ecd83cd440146c4bed3ef2d94f80c60001eb9
	t2.Mul(t2, t3)

	// Step 320: t2 = x^0x23da3081fb16be3b2f95d0090d70c4ecd83cd440146c4bed3ef2d94f80c60001eb90
	for s := 0; s < 4; s++ {
		t2.Square(t2)
	}

	// Step 321: t1 = x^0x23da3081fb16be3b2f95d0090d70c4ecd83cd440146c4bed3ef2d94f80c60001eb9d
	t1.Mul(t1, t2)

	// Step 329: t1 = x^0x23da3081fb16be3b2f95d0090d70c4ecd83cd440146c4bed3ef2d94f80c60001eb9d00
	for s := 0; s < 8; s++ {
		t1.Square(t1)
	}

	// Step 330: t0 = x^0x23da3081fb16be3b2f95d0090d70c4ecd83cd440146c4bed3ef2d94f80c60001eb9d1b
	t0.Mul(t0, t1)

	// Step 336: t0 = x^0x8f68c207ec5af8ecbe57402435c313b360f3510051b12fb4fbcb653e03180007ae746c0
	for s := 0; s < 6; s++ {
		t0.Square(t0)
	}

	// Step 337: t0 = x^0x8f68c207ec5af8ecbe57402435c313b360f3510051b12fb4fbcb653e03180007ae746c1
	t0.Mul(x, t0)

	// Step 371: t0 = x^0x23da3081fb16be3b2f95d0090d70c4ecd83cd440146c4bed3ef2d94f80c60001eb9d1b0400000000
	for s := 0; s < 34; s++ {
		t0.Square(t0)
	}

	// Step 372: t0 = x^0x23da3081fb16be3b2f95d0090d70c4ecd83cd440146c4bed3ef2d94f80c60001eb9d1b040000000b
	t0.Mul(z, t0)

	// Step 379: t0 = x^0x11ed1840fd8b5f1d97cae80486b862766c1e6a200a3625f69f796ca7c0630000f5ce8d820000000580
	for s := 0; s < 7; s++ {
		t0.Square(t0)
	}

	// Step 380: z = x^0x11ed1840fd8b5f1d97cae80486b862766c1e6a200a3625f69f796ca7c0630000f5ce8d82000000058b
	z.Mul(z, t0)

	// Step 385: z = x^0x23da3081fb16be3b2f95d0090d70c4ecd83cd440146c4bed3ef2d94f80c60001eb9d1b040000000b160
	for s := 0; s < 5; s++ {
		z.Square(z)
	}

	// Step 386: z = x^0x23da3081fb16be3b2f95d0090d70c4ecd83cd440146c4bed3ef2d94f80c60001eb9d1b040000000b161
	z.Mul(x, z)

	// Step 432: z = x^0x8f68c207ec5af8ecbe57402435c313b360f3510051b12fb4fbcb653e03180007ae746c100000002c58400000000000
	for s := 0; s < 46; s++ {
		z.Square(z)
	}

	return z
}
