package bls12377new

import (
	"crypto/rand"
	"math/big"

	"github.com/consensys/gnark-crypto/ecc"
	"github.com/yelhousni/batch-subgroup-membership/bls12377-new/fp"
	"github.com/yelhousni/batch-subgroup-membership/bls12377-new/fr"
)

// IsInSubGroupBatchNaive checks if a batch of points P_i are in G1.
// This is a naive method that checks each point individually using Scott test
// [Scott21].
//
// [Scott21]: https://eprint.iacr.org/2021/1130.pdf
func IsInSubGroupBatchNaive(points []G1Affine) bool {
	for i := range points {
		if !points[i].IsInSubGroup() {
			return false
		}
	}
	return true
}

// IsInSubGroupBatch checks if a batch of points P_i are in G1.
// First, it checks that all points are on a larger torsion E[r*e'] using Tate
// pairings [Koshelev22].
// Second, it generates random scalars s_i in the range [0, bound), performs
// n=rounds multi-scalar-multiplication Sj=∑[s_i]P_i of sizes N=len(points) and
// checks if Sj are on E[r] using Scott test [Scott21].
//
// [Koshelev22]: https://eprint.iacr.org/2022/037.pdf
// [Scott21]: https://eprint.iacr.org/2021/1130.pdf
func IsInSubGroupBatch(points []G1Affine, bound *big.Int, rounds int) bool {

	// 1. Check points are on E[r*e']
	for i := range points {
		// 1.1. Tate_{2,P2}(Q) == 1
		if !isFirstTateOne(points[i]) {
			return false
		}
		// 1.2. Tate_{3,P3}(Q) == 1
		if !isSecondTateOne(points[i]) {
			return false
		}
	}

	// 2. Check Sj are on E[r]
	for i := 0; i < rounds; i++ {
		randoms := make([]fr.Element, len(points))
		for j := range randoms {
			b, err := rand.Int(rand.Reader, bound)
			if err != nil {
				panic(err)
			}
			randoms[j].SetBigInt(b)
		}
		var sum G1Jac
		sum.MultiExp(points[:], randoms[:], ecc.MultiExpConfig{})
		if !sum.IsInSubGroup() {
			return false
		}
	}
	return true
}

// isFirstTateOne checks that Tate_{2,P2}(Q) = (x+1)^((p-1)/2) == 1
// where P2 = (-1,0) a point of order 2 on the
func isFirstTateOne(point G1Affine) bool {
	var tate, one fp.Element
	one.SetOne()
	tate.Add(&point.X, &one)
	tate = *expByp2(&tate)
	return tate.IsOne()
}

// isSecondTateOne checks that Tate_{3,P3}(Q) = (y-1)^((p-1)/3) == 1
// where P3 = (0,1) a point of order 3 on the
func isSecondTateOne(point G1Affine) bool {
	var tate, one fp.Element
	one.SetOne()
	tate.Sub(&point.Y, &one)
	tate = *expByp3(&tate)
	return tate.IsOne()
}

// expByp2 uses a short addition chain to compute x^p2 where p2=(p-1)/2 .
func expByp2(x *fp.Element) *fp.Element {
	// Operations: 370 squares 68 multiplies
	//
	// Generated by github.com/mmcloughlin/addchain v0.4.0.

	// Allocate Temporaries.
	var z = new(fp.Element)
	var (
		t0  = new(fp.Element)
		t1  = new(fp.Element)
		t2  = new(fp.Element)
		t3  = new(fp.Element)
		t4  = new(fp.Element)
		t5  = new(fp.Element)
		t6  = new(fp.Element)
		t7  = new(fp.Element)
		t8  = new(fp.Element)
		t9  = new(fp.Element)
		t10 = new(fp.Element)
		t11 = new(fp.Element)
		t12 = new(fp.Element)
		t13 = new(fp.Element)
		t14 = new(fp.Element)
		t15 = new(fp.Element)
		t16 = new(fp.Element)
		t17 = new(fp.Element)
		t18 = new(fp.Element)
		t19 = new(fp.Element)
		t20 = new(fp.Element)
		t21 = new(fp.Element)
		t22 = new(fp.Element)
		t23 = new(fp.Element)
		t24 = new(fp.Element)
	)

	// Step 1: t1 = x^0x2
	t1.Square(x)

	// Step 2: z = x^0x3
	z.Mul(x, t1)

	// Step 3: t18 = x^0x6
	t18.Square(z)

	// Step 4: t22 = x^0x7
	t22.Mul(x, t18)

	// Step 5: t0 = x^0x8
	t0.Mul(x, t22)

	// Step 6: t4 = x^0x9
	t4.Mul(x, t0)

	// Step 7: t14 = x^0xa
	t14.Mul(x, t4)

	// Step 8: t2 = x^0xd
	t2.Mul(z, t14)

	// Step 9: t7 = x^0x12
	t7.Mul(t0, t14)

	// Step 10: t8 = x^0x15
	t8.Mul(z, t7)

	// Step 11: t9 = x^0x17
	t9.Mul(t1, t8)

	// Step 12: t6 = x^0x1b
	t6.Mul(t18, t8)

	// Step 13: t12 = x^0x1d
	t12.Mul(t1, t6)

	// Step 14: t17 = x^0x1f
	t17.Mul(t1, t12)

	// Step 15: t5 = x^0x21
	t5.Mul(t1, t17)

	// Step 16: t19 = x^0x27
	t19.Mul(t18, t5)

	// Step 17: t20 = x^0x2b
	t20.Mul(t14, t5)

	// Step 18: t10 = x^0x2f
	t10.Mul(t0, t19)

	// Step 19: t13 = x^0x37
	t13.Mul(t0, t10)

	// Step 20: t15 = x^0x41
	t15.Mul(t14, t13)

	// Step 21: t3 = x^0x4b
	t3.Mul(t14, t15)

	// Step 22: t23 = x^0x4d
	t23.Mul(t1, t3)

	// Step 23: t21 = x^0x53
	t21.Mul(t18, t23)

	// Step 24: t16 = x^0x55
	t16.Mul(t1, t21)

	// Step 25: t7 = x^0x67
	t7.Mul(t7, t16)

	// Step 26: t11 = x^0x69
	t11.Mul(t1, t7)

	// Step 27: t18 = x^0x6f
	t18.Mul(t18, t11)

	// Step 28: t14 = x^0x73
	t14.Mul(t14, t11)

	// Step 29: t0 = x^0x7b
	t0.Mul(t0, t14)

	// Step 30: t24 = x^0xaa
	t24.Mul(t10, t0)

	// Step 37: t24 = x^0x5500
	for s := 0; s < 7; s++ {
		t24.Square(t24)
	}

	// Step 38: t24 = x^0x5555
	t24.Mul(t16, t24)

	// Step 46: t24 = x^0x555500
	for s := 0; s < 8; s++ {
		t24.Square(t24)
	}

	// Step 47: t24 = x^0x555555
	t24.Mul(t16, t24)

	// Step 55: t24 = x^0x55555500
	for s := 0; s < 8; s++ {
		t24.Square(t24)
	}

	// Step 56: t24 = x^0x55555555
	t24.Mul(t16, t24)

	// Step 64: t24 = x^0x5555555500
	for s := 0; s < 8; s++ {
		t24.Square(t24)
	}

	// Step 65: t24 = x^0x5555555555
	t24.Mul(t16, t24)

	// Step 73: t24 = x^0x555555555500
	for s := 0; s < 8; s++ {
		t24.Square(t24)
	}

	// Step 74: t24 = x^0x555555555555
	t24.Mul(t16, t24)

	// Step 81: t24 = x^0x2aaaaaaaaaaa80
	for s := 0; s < 7; s++ {
		t24.Square(t24)
	}

	// Step 82: t23 = x^0x2aaaaaaaaaaacd
	t23.Mul(t23, t24)

	// Step 86: t23 = x^0x2aaaaaaaaaaacd0
	for s := 0; s < 4; s++ {
		t23.Square(t23)
	}

	// Step 87: t22 = x^0x2aaaaaaaaaaacd7
	t22.Mul(t22, t23)

	// Step 133: t22 = x^0xaaaaaaaaaaab35c00000000000
	for s := 0; s < 46; s++ {
		t22.Square(t22)
	}

	// Step 134: t22 = x^0xaaaaaaaaaaab35c0000000002f
	t22.Mul(t10, t22)

	// Step 141: t22 = x^0x5555555555559ae0000000001780
	for s := 0; s < 7; s++ {
		t22.Square(t22)
	}

	// Step 142: t22 = x^0x5555555555559ae000000000179d
	t22.Mul(t12, t22)

	// Step 153: t22 = x^0x2aaaaaaaaaaacd70000000000bce800
	for s := 0; s < 11; s++ {
		t22.Square(t22)
	}

	// Step 154: t22 = x^0x2aaaaaaaaaaacd70000000000bce86f
	t22.Mul(t18, t22)

	// Step 165: t22 = x^0x15555555555566b80000000005e7437800
	for s := 0; s < 11; s++ {
		t22.Square(t22)
	}

	// Step 166: t22 = x^0x15555555555566b80000000005e7437855
	t22.Mul(t16, t22)

	// Step 174: t22 = x^0x15555555555566b80000000005e743785500
	for s := 0; s < 8; s++ {
		t22.Square(t22)
	}

	// Step 175: t22 = x^0x15555555555566b80000000005e743785555
	t22.Mul(t16, t22)

	// Step 182: t22 = x^0xaaaaaaaaaaab35c0000000002f3a1bc2aaa80
	for s := 0; s < 7; s++ {
		t22.Square(t22)
	}

	// Step 183: t22 = x^0xaaaaaaaaaaab35c0000000002f3a1bc2aaaab
	t22.Mul(t20, t22)

	// Step 192: t22 = x^0x15555555555566b80000000005e7437855555600
	for s := 0; s < 9; s++ {
		t22.Square(t22)
	}

	// Step 193: t22 = x^0x15555555555566b80000000005e7437855555667
	t22.Mul(t7, t22)

	// Step 205: t22 = x^0x15555555555566b80000000005e7437855555667000
	for s := 0; s < 12; s++ {
		t22.Square(t22)
	}

	// Step 206: t21 = x^0x15555555555566b80000000005e7437855555667053
	t21.Mul(t21, t22)

	// Step 216: t21 = x^0x5555555555559ae000000000179d0de15555599c14c00
	for s := 0; s < 10; s++ {
		t21.Square(t21)
	}

	// Step 217: t20 = x^0x5555555555559ae000000000179d0de15555599c14c2b
	t20.Mul(t20, t21)

	// Step 225: t20 = x^0x5555555555559ae000000000179d0de15555599c14c2b00
	for s := 0; s < 8; s++ {
		t20.Square(t20)
	}

	// Step 226: t19 = x^0x5555555555559ae000000000179d0de15555599c14c2b27
	t19.Mul(t19, t20)

	// Step 246: t19 = x^0x5555555555559ae000000000179d0de15555599c14c2b2700000
	for s := 0; s < 20; s++ {
		t19.Square(t19)
	}

	// Step 247: t18 = x^0x5555555555559ae000000000179d0de15555599c14c2b270006f
	t18.Mul(t18, t19)

	// Step 253: t18 = x^0x15555555555566b80000000005e74378555556670530ac9c001bc0
	for s := 0; s < 6; s++ {
		t18.Square(t18)
	}

	// Step 254: t18 = x^0x15555555555566b80000000005e74378555556670530ac9c001be1
	t18.Mul(t5, t18)

	// Step 263: t18 = x^0x2aaaaaaaaaaacd70000000000bce86f0aaaaacce0a6159380037c200
	for s := 0; s < 9; s++ {
		t18.Square(t18)
	}

	// Step 264: t18 = x^0x2aaaaaaaaaaacd70000000000bce86f0aaaaacce0a6159380037c27b
	t18.Mul(t0, t18)

	// Step 269: t18 = x^0x5555555555559ae000000000179d0de15555599c14c2b270006f84f60
	for s := 0; s < 5; s++ {
		t18.Square(t18)
	}

	// Step 270: t17 = x^0x5555555555559ae000000000179d0de15555599c14c2b270006f84f7f
	t17.Mul(t17, t18)

	// Step 280: t17 = x^0x15555555555566b80000000005e74378555556670530ac9c001be13dfc00
	for s := 0; s < 10; s++ {
		t17.Square(t17)
	}

	// Step 281: t17 = x^0x15555555555566b80000000005e74378555556670530ac9c001be13dfc21
	t17.Mul(t5, t17)

	// Step 291: t17 = x^0x5555555555559ae000000000179d0de15555599c14c2b270006f84f7f08400
	for s := 0; s < 10; s++ {
		t17.Square(t17)
	}

	// Step 292: t16 = x^0x5555555555559ae000000000179d0de15555599c14c2b270006f84f7f08455
	t16.Mul(t16, t17)

	// Step 301: t16 = x^0xaaaaaaaaaaab35c0000000002f3a1bc2aaaab338298564e000df09efe108aa00
	for s := 0; s < 9; s++ {
		t16.Square(t16)
	}

	// Step 302: t15 = x^0xaaaaaaaaaaab35c0000000002f3a1bc2aaaab338298564e000df09efe108aa41
	t15.Mul(t15, t16)

	// Step 310: t15 = x^0xaaaaaaaaaaab35c0000000002f3a1bc2aaaab338298564e000df09efe108aa4100
	for s := 0; s < 8; s++ {
		t15.Square(t15)
	}

	// Step 311: t14 = x^0xaaaaaaaaaaab35c0000000002f3a1bc2aaaab338298564e000df09efe108aa4173
	t14.Mul(t14, t15)

	// Step 318: t14 = x^0x5555555555559ae000000000179d0de15555599c14c2b270006f84f7f0845520b980
	for s := 0; s < 7; s++ {
		t14.Square(t14)
	}

	// Step 319: t13 = x^0x5555555555559ae000000000179d0de15555599c14c2b270006f84f7f0845520b9b7
	t13.Mul(t13, t14)

	// Step 326: t13 = x^0x2aaaaaaaaaaacd70000000000bce86f0aaaaacce0a6159380037c27bf8422a905cdb80
	for s := 0; s < 7; s++ {
		t13.Square(t13)
	}

	// Step 327: t12 = x^0x2aaaaaaaaaaacd70000000000bce86f0aaaaacce0a6159380037c27bf8422a905cdb9d
	t12.Mul(t12, t13)

	// Step 336: t12 = x^0x5555555555559ae000000000179d0de15555599c14c2b270006f84f7f0845520b9b73a00
	for s := 0; s < 9; s++ {
		t12.Square(t12)
	}

	// Step 337: t11 = x^0x5555555555559ae000000000179d0de15555599c14c2b270006f84f7f0845520b9b73a69
	t11.Mul(t11, t12)

	// Step 344: t11 = x^0x2aaaaaaaaaaacd70000000000bce86f0aaaaacce0a6159380037c27bf8422a905cdb9d3480
	for s := 0; s < 7; s++ {
		t11.Square(t11)
	}

	// Step 345: t10 = x^0x2aaaaaaaaaaacd70000000000bce86f0aaaaacce0a6159380037c27bf8422a905cdb9d34af
	t10.Mul(t10, t11)

	// Step 351: t10 = x^0xaaaaaaaaaaab35c0000000002f3a1bc2aaaab338298564e000df09efe108aa41736e74d2bc0
	for s := 0; s < 6; s++ {
		t10.Square(t10)
	}

	// Step 352: t9 = x^0xaaaaaaaaaaab35c0000000002f3a1bc2aaaab338298564e000df09efe108aa41736e74d2bd7
	t9.Mul(t9, t10)

	// Step 360: t9 = x^0xaaaaaaaaaaab35c0000000002f3a1bc2aaaab338298564e000df09efe108aa41736e74d2bd700
	for s := 0; s < 8; s++ {
		t9.Square(t9)
	}

	// Step 361: t8 = x^0xaaaaaaaaaaab35c0000000002f3a1bc2aaaab338298564e000df09efe108aa41736e74d2bd715
	t8.Mul(t8, t9)

	// Step 372: t8 = x^0x5555555555559ae000000000179d0de15555599c14c2b270006f84f7f0845520b9b73a695eb8a800
	for s := 0; s < 11; s++ {
		t8.Square(t8)
	}

	// Step 373: t7 = x^0x5555555555559ae000000000179d0de15555599c14c2b270006f84f7f0845520b9b73a695eb8a867
	t7.Mul(t7, t8)

	// Step 380: t7 = x^0x2aaaaaaaaaaacd70000000000bce86f0aaaaacce0a6159380037c27bf8422a905cdb9d34af5c543380
	for s := 0; s < 7; s++ {
		t7.Square(t7)
	}

	// Step 381: t6 = x^0x2aaaaaaaaaaacd70000000000bce86f0aaaaacce0a6159380037c27bf8422a905cdb9d34af5c54339b
	t6.Mul(t6, t7)

	// Step 391: t6 = x^0xaaaaaaaaaaab35c0000000002f3a1bc2aaaab338298564e000df09efe108aa41736e74d2bd7150ce6c00
	for s := 0; s < 10; s++ {
		t6.Square(t6)
	}

	// Step 392: t5 = x^0xaaaaaaaaaaab35c0000000002f3a1bc2aaaab338298564e000df09efe108aa41736e74d2bd7150ce6c21
	t5.Mul(t5, t6)

	// Step 403: t5 = x^0x5555555555559ae000000000179d0de15555599c14c2b270006f84f7f0845520b9b73a695eb8a8673610800
	for s := 0; s < 11; s++ {
		t5.Square(t5)
	}

	// Step 404: t4 = x^0x5555555555559ae000000000179d0de15555599c14c2b270006f84f7f0845520b9b73a695eb8a8673610809
	t4.Mul(t4, t5)

	// Step 416: t4 = x^0x5555555555559ae000000000179d0de15555599c14c2b270006f84f7f0845520b9b73a695eb8a8673610809000
	for s := 0; s < 12; s++ {
		t4.Square(t4)
	}

	// Step 417: t3 = x^0x5555555555559ae000000000179d0de15555599c14c2b270006f84f7f0845520b9b73a695eb8a867361080904b
	t3.Mul(t3, t4)

	// Step 422: t3 = x^0xaaaaaaaaaaab35c0000000002f3a1bc2aaaab338298564e000df09efe108aa41736e74d2bd7150ce6c210120960
	for s := 0; s < 5; s++ {
		t3.Square(t3)
	}

	// Step 423: t2 = x^0xaaaaaaaaaaab35c0000000002f3a1bc2aaaab338298564e000df09efe108aa41736e74d2bd7150ce6c21012096d
	t2.Mul(t2, t3)

	// Step 433: t2 = x^0x2aaaaaaaaaaacd70000000000bce86f0aaaaacce0a6159380037c27bf8422a905cdb9d34af5c54339b08404825b400
	for s := 0; s < 10; s++ {
		t2.Square(t2)
	}

	// Step 434: t1 = x^0x2aaaaaaaaaaacd70000000000bce86f0aaaaacce0a6159380037c27bf8422a905cdb9d34af5c54339b08404825b402
	t1.Mul(t1, t2)

	// Step 435: t0 = x^0x2aaaaaaaaaaacd70000000000bce86f0aaaaacce0a6159380037c27bf8422a905cdb9d34af5c54339b08404825b47d
	t0.Mul(t0, t1)

	// Step 437: t0 = x^0xaaaaaaaaaaab35c0000000002f3a1bc2aaaab338298564e000df09efe108aa41736e74d2bd7150ce6c21012096d1f4
	for s := 0; s < 2; s++ {
		t0.Square(t0)
	}

	// Step 438: z = x^0xaaaaaaaaaaab35c0000000002f3a1bc2aaaab338298564e000df09efe108aa41736e74d2bd7150ce6c21012096d1f7
	z.Mul(z, t0)

	return z
}

// expByp3 uses a short addition chain to compute x^p3 where p3=(p-1)/3 .
func expByp3(x *fp.Element) *fp.Element {
	// Operations: 371 squares 67 multiplies
	//
	// Generated by github.com/mmcloughlin/addchain v0.4.0.

	// Allocate Temporaries.
	var z = new(fp.Element)
	var (
		t0 = new(fp.Element)
		t1 = new(fp.Element)
		t2 = new(fp.Element)
		t3 = new(fp.Element)
		t4 = new(fp.Element)
		t5 = new(fp.Element)
		t6 = new(fp.Element)
		t7 = new(fp.Element)
		t8 = new(fp.Element)
	)

	// Step 1: z = x^0x2
	z.Square(x)

	// Step 2: t1 = x^0x3
	t1.Mul(x, z)

	// Step 3: t7 = x^0x5
	t7.Mul(z, t1)

	// Step 4: t4 = x^0x7
	t4.Mul(z, t7)

	// Step 5: t0 = x^0x9
	t0.Mul(z, t4)

	// Step 6: t2 = x^0xb
	t2.Mul(z, t0)

	// Step 7: t3 = x^0xd
	t3.Mul(z, t2)

	// Step 8: t6 = x^0xf
	t6.Mul(z, t3)

	// Step 9: z = x^0x1c
	z.Mul(t3, t6)

	// Step 10: t5 = x^0x1f
	t5.Mul(t1, z)

	// Step 11: t8 = x^0x38
	t8.Square(z)

	// Step 12: z = x^0x3f
	z.Mul(t4, t8)

	// Step 15: t8 = x^0x1c0
	for s := 0; s < 3; s++ {
		t8.Square(t8)
	}

	// Step 16: t8 = x^0x1c7
	t8.Mul(t4, t8)

	// Step 22: t8 = x^0x71c0
	for s := 0; s < 6; s++ {
		t8.Square(t8)
	}

	// Step 23: t8 = x^0x71c7
	t8.Mul(t4, t8)

	// Step 29: t8 = x^0x1c71c0
	for s := 0; s < 6; s++ {
		t8.Square(t8)
	}

	// Step 30: t8 = x^0x1c71c7
	t8.Mul(t4, t8)

	// Step 36: t8 = x^0x71c71c0
	for s := 0; s < 6; s++ {
		t8.Square(t8)
	}

	// Step 37: t8 = x^0x71c71c7
	t8.Mul(t4, t8)

	// Step 43: t8 = x^0x1c71c71c0
	for s := 0; s < 6; s++ {
		t8.Square(t8)
	}

	// Step 44: t8 = x^0x1c71c71c7
	t8.Mul(t4, t8)

	// Step 50: t8 = x^0x71c71c71c0
	for s := 0; s < 6; s++ {
		t8.Square(t8)
	}

	// Step 51: t8 = x^0x71c71c71c7
	t8.Mul(t4, t8)

	// Step 57: t8 = x^0x1c71c71c71c0
	for s := 0; s < 6; s++ {
		t8.Square(t8)
	}

	// Step 58: t8 = x^0x1c71c71c71c7
	t8.Mul(t4, t8)

	// Step 62: t8 = x^0x1c71c71c71c70
	for s := 0; s < 4; s++ {
		t8.Square(t8)
	}

	// Step 63: t8 = x^0x1c71c71c71c73
	t8.Mul(t1, t8)

	// Step 68: t8 = x^0x38e38e38e38e60
	for s := 0; s < 5; s++ {
		t8.Square(t8)
	}

	// Step 69: t8 = x^0x38e38e38e38e67
	t8.Mul(t4, t8)

	// Step 71: t8 = x^0xe38e38e38e399c
	for s := 0; s < 2; s++ {
		t8.Square(t8)
	}

	// Step 72: t8 = x^0xe38e38e38e399d
	t8.Mul(x, t8)

	// Step 119: t8 = x^0x71c71c71c71cce800000000000
	for s := 0; s < 47; s++ {
		t8.Square(t8)
	}

	// Step 120: t8 = x^0x71c71c71c71cce80000000001f
	t8.Mul(t5, t8)

	// Step 126: t8 = x^0x1c71c71c71c733a00000000007c0
	for s := 0; s < 6; s++ {
		t8.Square(t8)
	}

	// Step 127: t8 = x^0x1c71c71c71c733a00000000007df
	t8.Mul(t5, t8)

	// Step 136: t8 = x^0x38e38e38e38e6740000000000fbe00
	for s := 0; s < 9; s++ {
		t8.Square(t8)
	}

	// Step 137: t8 = x^0x38e38e38e38e6740000000000fbe09
	t8.Mul(t0, t8)

	// Step 139: t8 = x^0xe38e38e38e399d00000000003ef824
	for s := 0; s < 2; s++ {
		t8.Square(t8)
	}

	// Step 140: t8 = x^0xe38e38e38e399d00000000003ef825
	t8.Mul(x, t8)

	// Step 149: t8 = x^0x1c71c71c71c733a00000000007df04a00
	for s := 0; s < 9; s++ {
		t8.Square(t8)
	}

	// Step 150: t8 = x^0x1c71c71c71c733a00000000007df04a07
	t8.Mul(t4, t8)

	// Step 156: t8 = x^0x71c71c71c71cce80000000001f7c1281c0
	for s := 0; s < 6; s++ {
		t8.Square(t8)
	}

	// Step 157: t8 = x^0x71c71c71c71cce80000000001f7c1281c7
	t8.Mul(t4, t8)

	// Step 163: t8 = x^0x1c71c71c71c733a00000000007df04a071c0
	for s := 0; s < 6; s++ {
		t8.Square(t8)
	}

	// Step 164: t8 = x^0x1c71c71c71c733a00000000007df04a071c7
	t8.Mul(t4, t8)

	// Step 170: t8 = x^0x71c71c71c71cce80000000001f7c1281c71c0
	for s := 0; s < 6; s++ {
		t8.Square(t8)
	}

	// Step 171: t8 = x^0x71c71c71c71cce80000000001f7c1281c71c7
	t8.Mul(t4, t8)

	// Step 175: t8 = x^0x71c71c71c71cce80000000001f7c1281c71c70
	for s := 0; s < 4; s++ {
		t8.Square(t8)
	}

	// Step 176: t8 = x^0x71c71c71c71cce80000000001f7c1281c71c77
	t8.Mul(t4, t8)

	// Step 181: t8 = x^0xe38e38e38e399d00000000003ef825038e38ee0
	for s := 0; s < 5; s++ {
		t8.Square(t8)
	}

	// Step 182: t8 = x^0xe38e38e38e399d00000000003ef825038e38eef
	t8.Mul(t6, t8)

	// Step 187: t8 = x^0x1c71c71c71c733a00000000007df04a071c71dde0
	for s := 0; s < 5; s++ {
		t8.Square(t8)
	}

	// Step 188: t8 = x^0x1c71c71c71c733a00000000007df04a071c71ddeb
	t8.Mul(t2, t8)

	// Step 193: t8 = x^0x38e38e38e38e6740000000000fbe0940e38e3bbd60
	for s := 0; s < 5; s++ {
		t8.Square(t8)
	}

	// Step 194: t8 = x^0x38e38e38e38e6740000000000fbe0940e38e3bbd63
	t8.Mul(t1, t8)

	// Step 200: t8 = x^0xe38e38e38e399d00000000003ef825038e38eef58c0
	for s := 0; s < 6; s++ {
		t8.Square(t8)
	}

	// Step 201: t8 = x^0xe38e38e38e399d00000000003ef825038e38eef58cb
	t8.Mul(t2, t8)

	// Step 207: t8 = x^0x38e38e38e38e6740000000000fbe0940e38e3bbd632c0
	for s := 0; s < 6; s++ {
		t8.Square(t8)
	}

	// Step 208: t8 = x^0x38e38e38e38e6740000000000fbe0940e38e3bbd632c7
	t8.Mul(t4, t8)

	// Step 213: t8 = x^0x71c71c71c71cce80000000001f7c1281c71c777ac658e0
	for s := 0; s < 5; s++ {
		t8.Square(t8)
	}

	// Step 214: t8 = x^0x71c71c71c71cce80000000001f7c1281c71c777ac658ed
	t8.Mul(t3, t8)

	// Step 217: t8 = x^0x38e38e38e38e6740000000000fbe0940e38e3bbd632c768
	for s := 0; s < 3; s++ {
		t8.Square(t8)
	}

	// Step 218: t8 = x^0x38e38e38e38e6740000000000fbe0940e38e3bbd632c76f
	t8.Mul(t4, t8)

	// Step 222: t8 = x^0x38e38e38e38e6740000000000fbe0940e38e3bbd632c76f0
	for s := 0; s < 4; s++ {
		t8.Square(t8)
	}

	// Step 223: t8 = x^0x38e38e38e38e6740000000000fbe0940e38e3bbd632c76f5
	t8.Mul(t7, t8)

	// Step 227: t8 = x^0x38e38e38e38e6740000000000fbe0940e38e3bbd632c76f50
	for s := 0; s < 4; s++ {
		t8.Square(t8)
	}

	// Step 228: t8 = x^0x38e38e38e38e6740000000000fbe0940e38e3bbd632c76f55
	t8.Mul(t7, t8)

	// Step 233: t8 = x^0x71c71c71c71cce80000000001f7c1281c71c777ac658edeaa0
	for s := 0; s < 5; s++ {
		t8.Square(t8)
	}

	// Step 234: t8 = x^0x71c71c71c71cce80000000001f7c1281c71c777ac658edeaab
	t8.Mul(t2, t8)

	// Step 242: t8 = x^0x71c71c71c71cce80000000001f7c1281c71c777ac658edeaab00
	for s := 0; s < 8; s++ {
		t8.Square(t8)
	}

	// Step 243: t8 = x^0x71c71c71c71cce80000000001f7c1281c71c777ac658edeaab3f
	t8.Mul(z, t8)

	// Step 248: t8 = x^0xe38e38e38e399d00000000003ef825038e38eef58cb1dbd5567e0
	for s := 0; s < 5; s++ {
		t8.Square(t8)
	}

	// Step 249: t8 = x^0xe38e38e38e399d00000000003ef825038e38eef58cb1dbd5567eb
	t8.Mul(t2, t8)

	// Step 256: t8 = x^0x71c71c71c71cce80000000001f7c1281c71c777ac658edeaab3f580
	for s := 0; s < 7; s++ {
		t8.Square(t8)
	}

	// Step 257: t8 = x^0x71c71c71c71cce80000000001f7c1281c71c777ac658edeaab3f5bf
	t8.Mul(z, t8)

	// Step 261: t8 = x^0x71c71c71c71cce80000000001f7c1281c71c777ac658edeaab3f5bf0
	for s := 0; s < 4; s++ {
		t8.Square(t8)
	}

	// Step 262: t7 = x^0x71c71c71c71cce80000000001f7c1281c71c777ac658edeaab3f5bf5
	t7.Mul(t7, t8)

	// Step 264: t7 = x^0x1c71c71c71c733a00000000007df04a071c71ddeb1963b7aaacfd6fd4
	for s := 0; s < 2; s++ {
		t7.Square(t7)
	}

	// Step 265: t7 = x^0x1c71c71c71c733a00000000007df04a071c71ddeb1963b7aaacfd6fd5
	t7.Mul(x, t7)

	// Step 275: t7 = x^0x71c71c71c71cce80000000001f7c1281c71c777ac658edeaab3f5bf5400
	for s := 0; s < 10; s++ {
		t7.Square(t7)
	}

	// Step 276: t7 = x^0x71c71c71c71cce80000000001f7c1281c71c777ac658edeaab3f5bf540b
	t7.Mul(t2, t7)

	// Step 284: t7 = x^0x71c71c71c71cce80000000001f7c1281c71c777ac658edeaab3f5bf540b00
	for s := 0; s < 8; s++ {
		t7.Square(t7)
	}

	// Step 285: t7 = x^0x71c71c71c71cce80000000001f7c1281c71c777ac658edeaab3f5bf540b07
	t7.Mul(t4, t7)

	// Step 290: t7 = x^0xe38e38e38e399d00000000003ef825038e38eef58cb1dbd5567eb7ea8160e0
	for s := 0; s < 5; s++ {
		t7.Square(t7)
	}

	// Step 291: t7 = x^0xe38e38e38e399d00000000003ef825038e38eef58cb1dbd5567eb7ea8160e3
	t7.Mul(t1, t7)

	// Step 302: t7 = x^0x71c71c71c71cce80000000001f7c1281c71c777ac658edeaab3f5bf540b071800
	for s := 0; s < 11; s++ {
		t7.Square(t7)
	}

	// Step 303: t7 = x^0x71c71c71c71cce80000000001f7c1281c71c777ac658edeaab3f5bf540b07180f
	t7.Mul(t6, t7)

	// Step 308: t7 = x^0xe38e38e38e399d00000000003ef825038e38eef58cb1dbd5567eb7ea8160e301e0
	for s := 0; s < 5; s++ {
		t7.Square(t7)
	}

	// Step 309: t7 = x^0xe38e38e38e399d00000000003ef825038e38eef58cb1dbd5567eb7ea8160e301ef
	t7.Mul(t6, t7)

	// Step 315: t7 = x^0x38e38e38e38e6740000000000fbe0940e38e3bbd632c76f5559fadfaa05838c07bc0
	for s := 0; s < 6; s++ {
		t7.Square(t7)
	}

	// Step 316: t6 = x^0x38e38e38e38e6740000000000fbe0940e38e3bbd632c76f5559fadfaa05838c07bcf
	t6.Mul(t6, t7)

	// Step 322: t6 = x^0xe38e38e38e399d00000000003ef825038e38eef58cb1dbd5567eb7ea8160e301ef3c0
	for s := 0; s < 6; s++ {
		t6.Square(t6)
	}

	// Step 323: t5 = x^0xe38e38e38e399d00000000003ef825038e38eef58cb1dbd5567eb7ea8160e301ef3df
	t5.Mul(t5, t6)

	// Step 327: t5 = x^0xe38e38e38e399d00000000003ef825038e38eef58cb1dbd5567eb7ea8160e301ef3df0
	for s := 0; s < 4; s++ {
		t5.Square(t5)
	}

	// Step 328: t5 = x^0xe38e38e38e399d00000000003ef825038e38eef58cb1dbd5567eb7ea8160e301ef3df1
	t5.Mul(x, t5)

	// Step 333: t5 = x^0x1c71c71c71c733a00000000007df04a071c71ddeb1963b7aaacfd6fd502c1c603de7be20
	for s := 0; s < 5; s++ {
		t5.Square(t5)
	}

	// Step 334: t5 = x^0x1c71c71c71c733a00000000007df04a071c71ddeb1963b7aaacfd6fd502c1c603de7be23
	t5.Mul(t1, t5)

	// Step 343: t5 = x^0x38e38e38e38e6740000000000fbe0940e38e3bbd632c76f5559fadfaa05838c07bcf7c4600
	for s := 0; s < 9; s++ {
		t5.Square(t5)
	}

	// Step 344: t5 = x^0x38e38e38e38e6740000000000fbe0940e38e3bbd632c76f5559fadfaa05838c07bcf7c463f
	t5.Mul(z, t5)

	// Step 350: t5 = x^0xe38e38e38e399d00000000003ef825038e38eef58cb1dbd5567eb7ea8160e301ef3df118fc0
	for s := 0; s < 6; s++ {
		t5.Square(t5)
	}

	// Step 351: t5 = x^0xe38e38e38e399d00000000003ef825038e38eef58cb1dbd5567eb7ea8160e301ef3df118fc9
	t5.Mul(t0, t5)

	// Step 355: t5 = x^0xe38e38e38e399d00000000003ef825038e38eef58cb1dbd5567eb7ea8160e301ef3df118fc90
	for s := 0; s < 4; s++ {
		t5.Square(t5)
	}

	// Step 356: t4 = x^0xe38e38e38e399d00000000003ef825038e38eef58cb1dbd5567eb7ea8160e301ef3df118fc97
	t4.Mul(t4, t5)

	// Step 363: t4 = x^0x71c71c71c71cce80000000001f7c1281c71c777ac658edeaab3f5bf540b07180f79ef88c7e4b80
	for s := 0; s < 7; s++ {
		t4.Square(t4)
	}

	// Step 364: t4 = x^0x71c71c71c71cce80000000001f7c1281c71c777ac658edeaab3f5bf540b07180f79ef88c7e4b8b
	t4.Mul(t2, t4)

	// Step 370: t4 = x^0x1c71c71c71c733a00000000007df04a071c71ddeb1963b7aaacfd6fd502c1c603de7be231f92e2c0
	for s := 0; s < 6; s++ {
		t4.Square(t4)
	}

	// Step 371: t3 = x^0x1c71c71c71c733a00000000007df04a071c71ddeb1963b7aaacfd6fd502c1c603de7be231f92e2cd
	t3.Mul(t3, t4)

	// Step 378: t3 = x^0xe38e38e38e399d00000000003ef825038e38eef58cb1dbd5567eb7ea8160e301ef3df118fc9716680
	for s := 0; s < 7; s++ {
		t3.Square(t3)
	}

	// Step 379: t3 = x^0xe38e38e38e399d00000000003ef825038e38eef58cb1dbd5567eb7ea8160e301ef3df118fc9716689
	t3.Mul(t0, t3)

	// Step 389: t3 = x^0x38e38e38e38e6740000000000fbe0940e38e3bbd632c76f5559fadfaa05838c07bcf7c463f25c59a2400
	for s := 0; s < 10; s++ {
		t3.Square(t3)
	}

	// Step 390: t2 = x^0x38e38e38e38e6740000000000fbe0940e38e3bbd632c76f5559fadfaa05838c07bcf7c463f25c59a240b
	t2.Mul(t2, t3)

	// Step 401: t2 = x^0x1c71c71c71c733a00000000007df04a071c71ddeb1963b7aaacfd6fd502c1c603de7be231f92e2cd1205800
	for s := 0; s < 11; s++ {
		t2.Square(t2)
	}

	// Step 402: t2 = x^0x1c71c71c71c733a00000000007df04a071c71ddeb1963b7aaacfd6fd502c1c603de7be231f92e2cd1205803
	t2.Mul(t1, t2)

	// Step 411: t2 = x^0x38e38e38e38e6740000000000fbe0940e38e3bbd632c76f5559fadfaa05838c07bcf7c463f25c59a240b00600
	for s := 0; s < 9; s++ {
		t2.Square(t2)
	}

	// Step 412: t1 = x^0x38e38e38e38e6740000000000fbe0940e38e3bbd632c76f5559fadfaa05838c07bcf7c463f25c59a240b00603
	t1.Mul(t1, t2)

	// Step 418: t1 = x^0xe38e38e38e399d00000000003ef825038e38eef58cb1dbd5567eb7ea8160e301ef3df118fc971668902c0180c0
	for s := 0; s < 6; s++ {
		t1.Square(t1)
	}

	// Step 419: t0 = x^0xe38e38e38e399d00000000003ef825038e38eef58cb1dbd5567eb7ea8160e301ef3df118fc971668902c0180c9
	t0.Mul(t0, t1)

	// Step 423: t0 = x^0xe38e38e38e399d00000000003ef825038e38eef58cb1dbd5567eb7ea8160e301ef3df118fc971668902c0180c90
	for s := 0; s < 4; s++ {
		t0.Square(t0)
	}

	// Step 424: t0 = x^0xe38e38e38e399d00000000003ef825038e38eef58cb1dbd5567eb7ea8160e301ef3df118fc971668902c0180c91
	t0.Mul(x, t0)

	// Step 431: t0 = x^0x71c71c71c71cce80000000001f7c1281c71c777ac658edeaab3f5bf540b07180f79ef88c7e4b8b34481600c064880
	for s := 0; s < 7; s++ {
		t0.Square(t0)
	}

	// Step 432: z = x^0x71c71c71c71cce80000000001f7c1281c71c777ac658edeaab3f5bf540b07180f79ef88c7e4b8b34481600c0648bf
	z.Mul(z, t0)

	// Step 433: z = x^0xe38e38e38e399d00000000003ef825038e38eef58cb1dbd5567eb7ea8160e301ef3df118fc971668902c0180c917e
	z.Square(z)

	// Step 434: z = x^0xe38e38e38e399d00000000003ef825038e38eef58cb1dbd5567eb7ea8160e301ef3df118fc971668902c0180c917f
	z.Mul(x, z)

	// Step 436: z = x^0x38e38e38e38e6740000000000fbe0940e38e3bbd632c76f5559fadfaa05838c07bcf7c463f25c59a240b00603245fc
	for s := 0; s < 2; s++ {
		z.Square(z)
	}

	// Step 437: z = x^0x38e38e38e38e6740000000000fbe0940e38e3bbd632c76f5559fadfaa05838c07bcf7c463f25c59a240b00603245fd
	z.Mul(x, z)

	// Step 438: z = x^0x71c71c71c71cce80000000001f7c1281c71c777ac658edeaab3f5bf540b07180f79ef88c7e4b8b34481600c0648bfa
	z.Square(z)

	return z
}
