// Copyright 2020-2025 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package fp

// expBySqrtExp is equivalent to z.Exp(x, 3a9339a4671fa76944f5d69589f0e0d12f354435b26503d7b521d4a927be4e3d85c85bac7d00a204d4da072aaaaaab)
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) expBySqrtExp(x Element) *Element {
	// addition chain:
	//
	//	_10      = 2*1
	//	_100     = 2*_10
	//	_101     = 1 + _100
	//	_111     = _10 + _101
	//	_1000    = 1 + _111
	//	_1001    = 1 + _1000
	//	_1011    = _10 + _1001
	//	_1101    = _10 + _1011
	//	_1111    = _10 + _1101
	//	_10001   = _10 + _1111
	//	_10011   = _10 + _10001
	//	_10101   = _10 + _10011
	//	_11101   = _1000 + _10101
	//	_11111   = _10 + _11101
	//	_100001  = _10 + _11111
	//	_100011  = _10 + _100001
	//	_100101  = _10 + _100011
	//	_100111  = _10 + _100101
	//	_101001  = _10 + _100111
	//	_101011  = _10 + _101001
	//	_101101  = _10 + _101011
	//	_110001  = _100 + _101101
	//	_110011  = _10 + _110001
	//	_110101  = _10 + _110011
	//	_111001  = _100 + _110101
	//	_111011  = _10 + _111001
	//	_111101  = _10 + _111011
	//	_1110100 = _111001 + _111011
	//	i46      = ((_1110100 << 3 + _1001) << 8 + _110011) << 5
	//	i63      = ((_10011 + i46) << 5 + _1001) << 9 + _110011
	//	i85      = ((i63 << 6 + _100011) << 6 + _111101) << 8
	//	i104     = ((_111011 + i85) << 7 + _100101) << 9 + _100111
	//	i125     = ((i104 << 6 + _101011) << 6 + _101011) << 7
	//	i142     = ((_100101 + i125) << 7 + _110001) << 7 + _11111
	//	i169     = ((i142 << 7 + _111) << 9 + _1101) << 9
	//	i183     = ((_100101 + i169) << 6 + _111001) << 5 + _10101
	//	i205     = ((i183 << 6 + _10001) << 10 + _110101) << 4
	//	i220     = ((_1011 + i205) << 7 + _10011) << 5 + _101
	//	i246     = ((i220 << 12 + _111101) << 7 + _111101) << 5
	//	i263     = ((_10101 + i246) << 8 + _100001) << 6 + _110101
	//	i286     = ((i263 << 7 + _10101) << 6 + _1001) << 8
	//	i301     = ((_111101 + i286) << 4 + _1111) << 8 + _100111
	//	i325     = ((i301 << 9 + _111101) << 6 + _100001) << 7
	//	i344     = ((_111001 + i325) << 10 + _101101) << 6 + _110101
	//	i368     = ((i344 << 6 + _100011) << 5 + _11101) << 11
	//	i386     = ((_101 + i368) << 4 + 1) << 11 + _10011
	//	i413     = ((i386 << 7 + _101001) << 6 + _101101) << 12
	//	i428     = ((_111001 + i413) << 6 + _10101) << 6 + _10101
	//	i447     = ((i428 << 6 + _10101) << 6 + _10101) << 5
	//	return     _1011 + i447
	//
	// Operations: 369 squares 79 multiplies

	// Allocate Temporaries.
	var (
		t0  = new(Element)
		t1  = new(Element)
		t2  = new(Element)
		t3  = new(Element)
		t4  = new(Element)
		t5  = new(Element)
		t6  = new(Element)
		t7  = new(Element)
		t8  = new(Element)
		t9  = new(Element)
		t10 = new(Element)
		t11 = new(Element)
		t12 = new(Element)
		t13 = new(Element)
		t14 = new(Element)
		t15 = new(Element)
		t16 = new(Element)
		t17 = new(Element)
		t18 = new(Element)
		t19 = new(Element)
		t20 = new(Element)
		t21 = new(Element)
		t22 = new(Element)
		t23 = new(Element)
	)

	// var t0,t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15,t16,t17,t18,t19,t20,t21,t22,t23 Element
	// Step 1: t10 = x^0x2
	t10.Square(&x)

	// Step 2: t1 = x^0x4
	t1.Square(t10)

	// Step 3: t5 = x^0x5
	t5.Mul(&x, t1)

	// Step 4: t17 = x^0x7
	t17.Mul(t10, t5)

	// Step 5: t2 = x^0x8
	t2.Mul(&x, t17)

	// Step 6: t13 = x^0x9
	t13.Mul(&x, t2)

	// Step 7: z = x^0xb
	z.Mul(t10, t13)

	// Step 8: t16 = x^0xd
	t16.Mul(t10, z)

	// Step 9: t12 = x^0xf
	t12.Mul(t10, t16)

	// Step 10: t14 = x^0x11
	t14.Mul(t10, t12)

	// Step 11: t4 = x^0x13
	t4.Mul(t10, t14)

	// Step 12: t0 = x^0x15
	t0.Mul(t10, t4)

	// Step 13: t6 = x^0x1d
	t6.Mul(t2, t0)

	// Step 14: t18 = x^0x1f
	t18.Mul(t10, t6)

	// Step 15: t9 = x^0x21
	t9.Mul(t10, t18)

	// Step 16: t7 = x^0x23
	t7.Mul(t10, t9)

	// Step 17: t15 = x^0x25
	t15.Mul(t10, t7)

	// Step 18: t11 = x^0x27
	t11.Mul(t10, t15)

	// Step 19: t3 = x^0x29
	t3.Mul(t10, t11)

	// Step 20: t20 = x^0x2b
	t20.Mul(t10, t3)

	// Step 21: t2 = x^0x2d
	t2.Mul(t10, t20)

	// Step 22: t19 = x^0x31
	t19.Mul(t1, t2)

	// Step 23: t22 = x^0x33
	t22.Mul(t10, t19)

	// Step 24: t8 = x^0x35
	t8.Mul(t10, t22)

	// Step 25: t1 = x^0x39
	t1.Mul(t1, t8)

	// Step 26: t21 = x^0x3b
	t21.Mul(t10, t1)

	// Step 27: t10 = x^0x3d
	t10.Mul(t10, t21)

	// Step 28: t23 = x^0x74
	t23.Mul(t1, t21)

	// Step 31: t23 = x^0x3a0
	for s := 0; s < 3; s++ {
		t23.Square(t23)
	}

	// Step 32: t23 = x^0x3a9
	t23.Mul(t13, t23)

	// Step 40: t23 = x^0x3a900
	for s := 0; s < 8; s++ {
		t23.Square(t23)
	}

	// Step 41: t23 = x^0x3a933
	t23.Mul(t22, t23)

	// Step 46: t23 = x^0x752660
	for s := 0; s < 5; s++ {
		t23.Square(t23)
	}

	// Step 47: t23 = x^0x752673
	t23.Mul(t4, t23)

	// Step 52: t23 = x^0xea4ce60
	for s := 0; s < 5; s++ {
		t23.Square(t23)
	}

	// Step 53: t23 = x^0xea4ce69
	t23.Mul(t13, t23)

	// Step 62: t23 = x^0x1d499cd200
	for s := 0; s < 9; s++ {
		t23.Square(t23)
	}

	// Step 63: t22 = x^0x1d499cd233
	t22.Mul(t22, t23)

	// Step 69: t22 = x^0x75267348cc0
	for s := 0; s < 6; s++ {
		t22.Square(t22)
	}

	// Step 70: t22 = x^0x75267348ce3
	t22.Mul(t7, t22)

	// Step 76: t22 = x^0x1d499cd2338c0
	for s := 0; s < 6; s++ {
		t22.Square(t22)
	}

	// Step 77: t22 = x^0x1d499cd2338fd
	t22.Mul(t10, t22)

	// Step 85: t22 = x^0x1d499cd2338fd00
	for s := 0; s < 8; s++ {
		t22.Square(t22)
	}

	// Step 86: t21 = x^0x1d499cd2338fd3b
	t21.Mul(t21, t22)

	// Step 93: t21 = x^0xea4ce6919c7e9d80
	for s := 0; s < 7; s++ {
		t21.Square(t21)
	}

	// Step 94: t21 = x^0xea4ce6919c7e9da5
	t21.Mul(t15, t21)

	// Step 103: t21 = x^0x1d499cd2338fd3b4a00
	for s := 0; s < 9; s++ {
		t21.Square(t21)
	}

	// Step 104: t21 = x^0x1d499cd2338fd3b4a27
	t21.Mul(t11, t21)

	// Step 110: t21 = x^0x75267348ce3f4ed289c0
	for s := 0; s < 6; s++ {
		t21.Square(t21)
	}

	// Step 111: t21 = x^0x75267348ce3f4ed289eb
	t21.Mul(t20, t21)

	// Step 117: t21 = x^0x1d499cd2338fd3b4a27ac0
	for s := 0; s < 6; s++ {
		t21.Square(t21)
	}

	// Step 118: t20 = x^0x1d499cd2338fd3b4a27aeb
	t20.Mul(t20, t21)

	// Step 125: t20 = x^0xea4ce6919c7e9da513d7580
	for s := 0; s < 7; s++ {
		t20.Square(t20)
	}

	// Step 126: t20 = x^0xea4ce6919c7e9da513d75a5
	t20.Mul(t15, t20)

	// Step 133: t20 = x^0x75267348ce3f4ed289ebad280
	for s := 0; s < 7; s++ {
		t20.Square(t20)
	}

	// Step 134: t19 = x^0x75267348ce3f4ed289ebad2b1
	t19.Mul(t19, t20)

	// Step 141: t19 = x^0x3a9339a4671fa76944f5d695880
	for s := 0; s < 7; s++ {
		t19.Square(t19)
	}

	// Step 142: t18 = x^0x3a9339a4671fa76944f5d69589f
	t18.Mul(t18, t19)

	// Step 149: t18 = x^0x1d499cd2338fd3b4a27aeb4ac4f80
	for s := 0; s < 7; s++ {
		t18.Square(t18)
	}

	// Step 150: t17 = x^0x1d499cd2338fd3b4a27aeb4ac4f87
	t17.Mul(t17, t18)

	// Step 159: t17 = x^0x3a9339a4671fa76944f5d69589f0e00
	for s := 0; s < 9; s++ {
		t17.Square(t17)
	}

	// Step 160: t16 = x^0x3a9339a4671fa76944f5d69589f0e0d
	t16.Mul(t16, t17)

	// Step 169: t16 = x^0x75267348ce3f4ed289ebad2b13e1c1a00
	for s := 0; s < 9; s++ {
		t16.Square(t16)
	}

	// Step 170: t15 = x^0x75267348ce3f4ed289ebad2b13e1c1a25
	t15.Mul(t15, t16)

	// Step 176: t15 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068940
	for s := 0; s < 6; s++ {
		t15.Square(t15)
	}

	// Step 177: t15 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979
	t15.Mul(t1, t15)

	// Step 182: t15 = x^0x3a9339a4671fa76944f5d69589f0e0d12f20
	for s := 0; s < 5; s++ {
		t15.Square(t15)
	}

	// Step 183: t15 = x^0x3a9339a4671fa76944f5d69589f0e0d12f35
	t15.Mul(t0, t15)

	// Step 189: t15 = x^0xea4ce6919c7e9da513d75a5627c38344bcd40
	for s := 0; s < 6; s++ {
		t15.Square(t15)
	}

	// Step 190: t14 = x^0xea4ce6919c7e9da513d75a5627c38344bcd51
	t14.Mul(t14, t15)

	// Step 200: t14 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354400
	for s := 0; s < 10; s++ {
		t14.Square(t14)
	}

	// Step 201: t14 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435
	t14.Mul(t8, t14)

	// Step 205: t14 = x^0x3a9339a4671fa76944f5d69589f0e0d12f3544350
	for s := 0; s < 4; s++ {
		t14.Square(t14)
	}

	// Step 206: t14 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b
	t14.Mul(z, t14)

	// Step 213: t14 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad80
	for s := 0; s < 7; s++ {
		t14.Square(t14)
	}

	// Step 214: t14 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93
	t14.Mul(t4, t14)

	// Step 219: t14 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b260
	for s := 0; s < 5; s++ {
		t14.Square(t14)
	}

	// Step 220: t14 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b265
	t14.Mul(t5, t14)

	// Step 232: t14 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b265000
	for s := 0; s < 12; s++ {
		t14.Square(t14)
	}

	// Step 233: t14 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b26503d
	t14.Mul(t10, t14)

	// Step 240: t14 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281e80
	for s := 0; s < 7; s++ {
		t14.Square(t14)
	}

	// Step 241: t14 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebd
	t14.Mul(t10, t14)

	// Step 246: t14 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b26503d7a0
	for s := 0; s < 5; s++ {
		t14.Square(t14)
	}

	// Step 247: t14 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b26503d7b5
	t14.Mul(t0, t14)

	// Step 255: t14 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b26503d7b500
	for s := 0; s < 8; s++ {
		t14.Square(t14)
	}

	// Step 256: t14 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b26503d7b521
	t14.Mul(t9, t14)

	// Step 262: t14 = x^0xea4ce6919c7e9da513d75a5627c38344bcd510d6c9940f5ed4840
	for s := 0; s < 6; s++ {
		t14.Square(t14)
	}

	// Step 263: t14 = x^0xea4ce6919c7e9da513d75a5627c38344bcd510d6c9940f5ed4875
	t14.Mul(t8, t14)

	// Step 270: t14 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a80
	for s := 0; s < 7; s++ {
		t14.Square(t14)
	}

	// Step 271: t14 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a95
	t14.Mul(t0, t14)

	// Step 277: t14 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea540
	for s := 0; s < 6; s++ {
		t14.Square(t14)
	}

	// Step 278: t13 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea549
	t13.Mul(t13, t14)

	// Step 286: t13 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea54900
	for s := 0; s < 8; s++ {
		t13.Square(t13)
	}

	// Step 287: t13 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493d
	t13.Mul(t10, t13)

	// Step 291: t13 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493d0
	for s := 0; s < 4; s++ {
		t13.Square(t13)
	}

	// Step 292: t12 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df
	t12.Mul(t12, t13)

	// Step 300: t12 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df00
	for s := 0; s < 8; s++ {
		t12.Square(t12)
	}

	// Step 301: t11 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df27
	t11.Mul(t11, t12)

	// Step 310: t11 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b26503d7b521d4a927be4e00
	for s := 0; s < 9; s++ {
		t11.Square(t11)
	}

	// Step 311: t10 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b26503d7b521d4a927be4e3d
	t10.Mul(t10, t11)

	// Step 317: t10 = x^0xea4ce6919c7e9da513d75a5627c38344bcd510d6c9940f5ed48752a49ef938f40
	for s := 0; s < 6; s++ {
		t10.Square(t10)
	}

	// Step 318: t9 = x^0xea4ce6919c7e9da513d75a5627c38344bcd510d6c9940f5ed48752a49ef938f61
	t9.Mul(t9, t10)

	// Step 325: t9 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a9524f7c9c7b080
	for s := 0; s < 7; s++ {
		t9.Square(t9)
	}

	// Step 326: t9 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a9524f7c9c7b0b9
	t9.Mul(t1, t9)

	// Step 336: t9 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e400
	for s := 0; s < 10; s++ {
		t9.Square(t9)
	}

	// Step 337: t9 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42d
	t9.Mul(t2, t9)

	// Step 343: t9 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a9524f7c9c7b0b90b40
	for s := 0; s < 6; s++ {
		t9.Square(t9)
	}

	// Step 344: t8 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a9524f7c9c7b0b90b75
	t8.Mul(t8, t9)

	// Step 350: t8 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd40
	for s := 0; s < 6; s++ {
		t8.Square(t8)
	}

	// Step 351: t7 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63
	t7.Mul(t7, t8)

	// Step 356: t7 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b26503d7b521d4a927be4e3d85c85bac60
	for s := 0; s < 5; s++ {
		t7.Square(t7)
	}

	// Step 357: t6 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b26503d7b521d4a927be4e3d85c85bac7d
	t6.Mul(t6, t7)

	// Step 368: t6 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63e800
	for s := 0; s < 11; s++ {
		t6.Square(t6)
	}

	// Step 369: t5 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63e805
	t5.Mul(t5, t6)

	// Step 373: t5 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63e8050
	for s := 0; s < 4; s++ {
		t5.Square(t5)
	}

	// Step 374: t5 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63e8051
	t5.Mul(&x, t5)

	// Step 385: t5 = x^0xea4ce6919c7e9da513d75a5627c38344bcd510d6c9940f5ed48752a49ef938f617216eb1f4028800
	for s := 0; s < 11; s++ {
		t5.Square(t5)
	}

	// Step 386: t4 = x^0xea4ce6919c7e9da513d75a5627c38344bcd510d6c9940f5ed48752a49ef938f617216eb1f4028813
	t4.Mul(t4, t5)

	// Step 393: t4 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a9524f7c9c7b0b90b758fa01440980
	for s := 0; s < 7; s++ {
		t4.Square(t4)
	}

	// Step 394: t3 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a9524f7c9c7b0b90b758fa014409a9
	t3.Mul(t3, t4)

	// Step 400: t3 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63e8051026a40
	for s := 0; s < 6; s++ {
		t3.Square(t3)
	}

	// Step 401: t2 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63e8051026a6d
	t2.Mul(t2, t3)

	// Step 413: t2 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63e8051026a6d000
	for s := 0; s < 12; s++ {
		t2.Square(t2)
	}

	// Step 414: t1 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63e8051026a6d039
	t1.Mul(t1, t2)

	// Step 420: t1 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a9524f7c9c7b0b90b758fa014409a9b40e40
	for s := 0; s < 6; s++ {
		t1.Square(t1)
	}

	// Step 421: t1 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a9524f7c9c7b0b90b758fa014409a9b40e55
	t1.Mul(t0, t1)

	// Step 427: t1 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63e8051026a6d039540
	for s := 0; s < 6; s++ {
		t1.Square(t1)
	}

	// Step 428: t1 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63e8051026a6d039555
	t1.Mul(t0, t1)

	// Step 434: t1 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a9524f7c9c7b0b90b758fa014409a9b40e55540
	for s := 0; s < 6; s++ {
		t1.Square(t1)
	}

	// Step 435: t1 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a9524f7c9c7b0b90b758fa014409a9b40e55555
	t1.Mul(t0, t1)

	// Step 441: t1 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63e8051026a6d039555540
	for s := 0; s < 6; s++ {
		t1.Square(t1)
	}

	// Step 442: t0 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63e8051026a6d039555555
	t0.Mul(t0, t1)

	// Step 447: t0 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b26503d7b521d4a927be4e3d85c85bac7d00a204d4da072aaaaaa0
	for s := 0; s < 5; s++ {
		t0.Square(t0)
	}

	// Step 448: z = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b26503d7b521d4a927be4e3d85c85bac7d00a204d4da072aaaaaab
	z.Mul(z, t0)

	return z
}

// expByLegendreExp is equivalent to z.Exp(x, 75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a9524f7c9c7b0b90b758fa014409a9b40e55555555)
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) expByLegendreExp(x Element) *Element {
	// addition chain:
	//
	//	_10      = 2*1
	//	_100     = 2*_10
	//	_101     = 1 + _100
	//	_111     = _10 + _101
	//	_1000    = 1 + _111
	//	_1001    = 1 + _1000
	//	_1011    = _10 + _1001
	//	_1101    = _10 + _1011
	//	_1111    = _10 + _1101
	//	_10001   = _10 + _1111
	//	_10011   = _10 + _10001
	//	_10101   = _10 + _10011
	//	_11101   = _1000 + _10101
	//	_11111   = _10 + _11101
	//	_100001  = _10 + _11111
	//	_100011  = _10 + _100001
	//	_100101  = _10 + _100011
	//	_100111  = _10 + _100101
	//	_101001  = _10 + _100111
	//	_101011  = _10 + _101001
	//	_101101  = _10 + _101011
	//	_110001  = _100 + _101101
	//	_110011  = _10 + _110001
	//	_110101  = _10 + _110011
	//	_111001  = _100 + _110101
	//	_111011  = _10 + _111001
	//	_111101  = _10 + _111011
	//	_1110100 = _111001 + _111011
	//	i46      = ((_1110100 << 3 + _1001) << 8 + _110011) << 5
	//	i63      = ((_10011 + i46) << 5 + _1001) << 9 + _110011
	//	i85      = ((i63 << 6 + _100011) << 6 + _111101) << 8
	//	i104     = ((_111011 + i85) << 7 + _100101) << 9 + _100111
	//	i125     = ((i104 << 6 + _101011) << 6 + _101011) << 7
	//	i142     = ((_100101 + i125) << 7 + _110001) << 7 + _11111
	//	i169     = ((i142 << 7 + _111) << 9 + _1101) << 9
	//	i183     = ((_100101 + i169) << 6 + _111001) << 5 + _10101
	//	i205     = ((i183 << 6 + _10001) << 10 + _110101) << 4
	//	i220     = ((_1011 + i205) << 7 + _10011) << 5 + _101
	//	i246     = ((i220 << 12 + _111101) << 7 + _111101) << 5
	//	i263     = ((_10101 + i246) << 8 + _100001) << 6 + _110101
	//	i286     = ((i263 << 7 + _10101) << 6 + _1001) << 8
	//	i301     = ((_111101 + i286) << 4 + _1111) << 8 + _100111
	//	i325     = ((i301 << 9 + _111101) << 6 + _100001) << 7
	//	i344     = ((_111001 + i325) << 10 + _101101) << 6 + _110101
	//	i368     = ((i344 << 6 + _100011) << 5 + _11101) << 11
	//	i386     = ((_101 + i368) << 4 + 1) << 11 + _10011
	//	i413     = ((i386 << 7 + _101001) << 6 + _101101) << 12
	//	i428     = ((_111001 + i413) << 6 + _10101) << 6 + _10101
	//	i448     = ((i428 << 6 + _10101) << 6 + _10101) << 6
	//	return     _10101 + i448
	//
	// Operations: 370 squares 79 multiplies

	// Allocate Temporaries.
	var (
		t0  = new(Element)
		t1  = new(Element)
		t2  = new(Element)
		t3  = new(Element)
		t4  = new(Element)
		t5  = new(Element)
		t6  = new(Element)
		t7  = new(Element)
		t8  = new(Element)
		t9  = new(Element)
		t10 = new(Element)
		t11 = new(Element)
		t12 = new(Element)
		t13 = new(Element)
		t14 = new(Element)
		t15 = new(Element)
		t16 = new(Element)
		t17 = new(Element)
		t18 = new(Element)
		t19 = new(Element)
		t20 = new(Element)
		t21 = new(Element)
		t22 = new(Element)
		t23 = new(Element)
	)

	// var t0,t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15,t16,t17,t18,t19,t20,t21,t22,t23 Element
	// Step 1: t9 = x^0x2
	t9.Square(&x)

	// Step 2: t0 = x^0x4
	t0.Square(t9)

	// Step 3: t4 = x^0x5
	t4.Mul(&x, t0)

	// Step 4: t17 = x^0x7
	t17.Mul(t9, t4)

	// Step 5: t1 = x^0x8
	t1.Mul(&x, t17)

	// Step 6: t12 = x^0x9
	t12.Mul(&x, t1)

	// Step 7: t13 = x^0xb
	t13.Mul(t9, t12)

	// Step 8: t16 = x^0xd
	t16.Mul(t9, t13)

	// Step 9: t11 = x^0xf
	t11.Mul(t9, t16)

	// Step 10: t14 = x^0x11
	t14.Mul(t9, t11)

	// Step 11: t3 = x^0x13
	t3.Mul(t9, t14)

	// Step 12: z = x^0x15
	z.Mul(t9, t3)

	// Step 13: t5 = x^0x1d
	t5.Mul(t1, z)

	// Step 14: t18 = x^0x1f
	t18.Mul(t9, t5)

	// Step 15: t8 = x^0x21
	t8.Mul(t9, t18)

	// Step 16: t6 = x^0x23
	t6.Mul(t9, t8)

	// Step 17: t15 = x^0x25
	t15.Mul(t9, t6)

	// Step 18: t10 = x^0x27
	t10.Mul(t9, t15)

	// Step 19: t2 = x^0x29
	t2.Mul(t9, t10)

	// Step 20: t20 = x^0x2b
	t20.Mul(t9, t2)

	// Step 21: t1 = x^0x2d
	t1.Mul(t9, t20)

	// Step 22: t19 = x^0x31
	t19.Mul(t0, t1)

	// Step 23: t22 = x^0x33
	t22.Mul(t9, t19)

	// Step 24: t7 = x^0x35
	t7.Mul(t9, t22)

	// Step 25: t0 = x^0x39
	t0.Mul(t0, t7)

	// Step 26: t21 = x^0x3b
	t21.Mul(t9, t0)

	// Step 27: t9 = x^0x3d
	t9.Mul(t9, t21)

	// Step 28: t23 = x^0x74
	t23.Mul(t0, t21)

	// Step 31: t23 = x^0x3a0
	for s := 0; s < 3; s++ {
		t23.Square(t23)
	}

	// Step 32: t23 = x^0x3a9
	t23.Mul(t12, t23)

	// Step 40: t23 = x^0x3a900
	for s := 0; s < 8; s++ {
		t23.Square(t23)
	}

	// Step 41: t23 = x^0x3a933
	t23.Mul(t22, t23)

	// Step 46: t23 = x^0x752660
	for s := 0; s < 5; s++ {
		t23.Square(t23)
	}

	// Step 47: t23 = x^0x752673
	t23.Mul(t3, t23)

	// Step 52: t23 = x^0xea4ce60
	for s := 0; s < 5; s++ {
		t23.Square(t23)
	}

	// Step 53: t23 = x^0xea4ce69
	t23.Mul(t12, t23)

	// Step 62: t23 = x^0x1d499cd200
	for s := 0; s < 9; s++ {
		t23.Square(t23)
	}

	// Step 63: t22 = x^0x1d499cd233
	t22.Mul(t22, t23)

	// Step 69: t22 = x^0x75267348cc0
	for s := 0; s < 6; s++ {
		t22.Square(t22)
	}

	// Step 70: t22 = x^0x75267348ce3
	t22.Mul(t6, t22)

	// Step 76: t22 = x^0x1d499cd2338c0
	for s := 0; s < 6; s++ {
		t22.Square(t22)
	}

	// Step 77: t22 = x^0x1d499cd2338fd
	t22.Mul(t9, t22)

	// Step 85: t22 = x^0x1d499cd2338fd00
	for s := 0; s < 8; s++ {
		t22.Square(t22)
	}

	// Step 86: t21 = x^0x1d499cd2338fd3b
	t21.Mul(t21, t22)

	// Step 93: t21 = x^0xea4ce6919c7e9d80
	for s := 0; s < 7; s++ {
		t21.Square(t21)
	}

	// Step 94: t21 = x^0xea4ce6919c7e9da5
	t21.Mul(t15, t21)

	// Step 103: t21 = x^0x1d499cd2338fd3b4a00
	for s := 0; s < 9; s++ {
		t21.Square(t21)
	}

	// Step 104: t21 = x^0x1d499cd2338fd3b4a27
	t21.Mul(t10, t21)

	// Step 110: t21 = x^0x75267348ce3f4ed289c0
	for s := 0; s < 6; s++ {
		t21.Square(t21)
	}

	// Step 111: t21 = x^0x75267348ce3f4ed289eb
	t21.Mul(t20, t21)

	// Step 117: t21 = x^0x1d499cd2338fd3b4a27ac0
	for s := 0; s < 6; s++ {
		t21.Square(t21)
	}

	// Step 118: t20 = x^0x1d499cd2338fd3b4a27aeb
	t20.Mul(t20, t21)

	// Step 125: t20 = x^0xea4ce6919c7e9da513d7580
	for s := 0; s < 7; s++ {
		t20.Square(t20)
	}

	// Step 126: t20 = x^0xea4ce6919c7e9da513d75a5
	t20.Mul(t15, t20)

	// Step 133: t20 = x^0x75267348ce3f4ed289ebad280
	for s := 0; s < 7; s++ {
		t20.Square(t20)
	}

	// Step 134: t19 = x^0x75267348ce3f4ed289ebad2b1
	t19.Mul(t19, t20)

	// Step 141: t19 = x^0x3a9339a4671fa76944f5d695880
	for s := 0; s < 7; s++ {
		t19.Square(t19)
	}

	// Step 142: t18 = x^0x3a9339a4671fa76944f5d69589f
	t18.Mul(t18, t19)

	// Step 149: t18 = x^0x1d499cd2338fd3b4a27aeb4ac4f80
	for s := 0; s < 7; s++ {
		t18.Square(t18)
	}

	// Step 150: t17 = x^0x1d499cd2338fd3b4a27aeb4ac4f87
	t17.Mul(t17, t18)

	// Step 159: t17 = x^0x3a9339a4671fa76944f5d69589f0e00
	for s := 0; s < 9; s++ {
		t17.Square(t17)
	}

	// Step 160: t16 = x^0x3a9339a4671fa76944f5d69589f0e0d
	t16.Mul(t16, t17)

	// Step 169: t16 = x^0x75267348ce3f4ed289ebad2b13e1c1a00
	for s := 0; s < 9; s++ {
		t16.Square(t16)
	}

	// Step 170: t15 = x^0x75267348ce3f4ed289ebad2b13e1c1a25
	t15.Mul(t15, t16)

	// Step 176: t15 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068940
	for s := 0; s < 6; s++ {
		t15.Square(t15)
	}

	// Step 177: t15 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979
	t15.Mul(t0, t15)

	// Step 182: t15 = x^0x3a9339a4671fa76944f5d69589f0e0d12f20
	for s := 0; s < 5; s++ {
		t15.Square(t15)
	}

	// Step 183: t15 = x^0x3a9339a4671fa76944f5d69589f0e0d12f35
	t15.Mul(z, t15)

	// Step 189: t15 = x^0xea4ce6919c7e9da513d75a5627c38344bcd40
	for s := 0; s < 6; s++ {
		t15.Square(t15)
	}

	// Step 190: t14 = x^0xea4ce6919c7e9da513d75a5627c38344bcd51
	t14.Mul(t14, t15)

	// Step 200: t14 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354400
	for s := 0; s < 10; s++ {
		t14.Square(t14)
	}

	// Step 201: t14 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435
	t14.Mul(t7, t14)

	// Step 205: t14 = x^0x3a9339a4671fa76944f5d69589f0e0d12f3544350
	for s := 0; s < 4; s++ {
		t14.Square(t14)
	}

	// Step 206: t13 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b
	t13.Mul(t13, t14)

	// Step 213: t13 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad80
	for s := 0; s < 7; s++ {
		t13.Square(t13)
	}

	// Step 214: t13 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93
	t13.Mul(t3, t13)

	// Step 219: t13 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b260
	for s := 0; s < 5; s++ {
		t13.Square(t13)
	}

	// Step 220: t13 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b265
	t13.Mul(t4, t13)

	// Step 232: t13 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b265000
	for s := 0; s < 12; s++ {
		t13.Square(t13)
	}

	// Step 233: t13 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b26503d
	t13.Mul(t9, t13)

	// Step 240: t13 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281e80
	for s := 0; s < 7; s++ {
		t13.Square(t13)
	}

	// Step 241: t13 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebd
	t13.Mul(t9, t13)

	// Step 246: t13 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b26503d7a0
	for s := 0; s < 5; s++ {
		t13.Square(t13)
	}

	// Step 247: t13 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b26503d7b5
	t13.Mul(z, t13)

	// Step 255: t13 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b26503d7b500
	for s := 0; s < 8; s++ {
		t13.Square(t13)
	}

	// Step 256: t13 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b26503d7b521
	t13.Mul(t8, t13)

	// Step 262: t13 = x^0xea4ce6919c7e9da513d75a5627c38344bcd510d6c9940f5ed4840
	for s := 0; s < 6; s++ {
		t13.Square(t13)
	}

	// Step 263: t13 = x^0xea4ce6919c7e9da513d75a5627c38344bcd510d6c9940f5ed4875
	t13.Mul(t7, t13)

	// Step 270: t13 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a80
	for s := 0; s < 7; s++ {
		t13.Square(t13)
	}

	// Step 271: t13 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a95
	t13.Mul(z, t13)

	// Step 277: t13 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea540
	for s := 0; s < 6; s++ {
		t13.Square(t13)
	}

	// Step 278: t12 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea549
	t12.Mul(t12, t13)

	// Step 286: t12 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea54900
	for s := 0; s < 8; s++ {
		t12.Square(t12)
	}

	// Step 287: t12 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493d
	t12.Mul(t9, t12)

	// Step 291: t12 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493d0
	for s := 0; s < 4; s++ {
		t12.Square(t12)
	}

	// Step 292: t11 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df
	t11.Mul(t11, t12)

	// Step 300: t11 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df00
	for s := 0; s < 8; s++ {
		t11.Square(t11)
	}

	// Step 301: t10 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df27
	t10.Mul(t10, t11)

	// Step 310: t10 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b26503d7b521d4a927be4e00
	for s := 0; s < 9; s++ {
		t10.Square(t10)
	}

	// Step 311: t9 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b26503d7b521d4a927be4e3d
	t9.Mul(t9, t10)

	// Step 317: t9 = x^0xea4ce6919c7e9da513d75a5627c38344bcd510d6c9940f5ed48752a49ef938f40
	for s := 0; s < 6; s++ {
		t9.Square(t9)
	}

	// Step 318: t8 = x^0xea4ce6919c7e9da513d75a5627c38344bcd510d6c9940f5ed48752a49ef938f61
	t8.Mul(t8, t9)

	// Step 325: t8 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a9524f7c9c7b080
	for s := 0; s < 7; s++ {
		t8.Square(t8)
	}

	// Step 326: t8 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a9524f7c9c7b0b9
	t8.Mul(t0, t8)

	// Step 336: t8 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e400
	for s := 0; s < 10; s++ {
		t8.Square(t8)
	}

	// Step 337: t8 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42d
	t8.Mul(t1, t8)

	// Step 343: t8 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a9524f7c9c7b0b90b40
	for s := 0; s < 6; s++ {
		t8.Square(t8)
	}

	// Step 344: t7 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a9524f7c9c7b0b90b75
	t7.Mul(t7, t8)

	// Step 350: t7 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd40
	for s := 0; s < 6; s++ {
		t7.Square(t7)
	}

	// Step 351: t6 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63
	t6.Mul(t6, t7)

	// Step 356: t6 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b26503d7b521d4a927be4e3d85c85bac60
	for s := 0; s < 5; s++ {
		t6.Square(t6)
	}

	// Step 357: t5 = x^0x3a9339a4671fa76944f5d69589f0e0d12f354435b26503d7b521d4a927be4e3d85c85bac7d
	t5.Mul(t5, t6)

	// Step 368: t5 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63e800
	for s := 0; s < 11; s++ {
		t5.Square(t5)
	}

	// Step 369: t4 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63e805
	t4.Mul(t4, t5)

	// Step 373: t4 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63e8050
	for s := 0; s < 4; s++ {
		t4.Square(t4)
	}

	// Step 374: t4 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63e8051
	t4.Mul(&x, t4)

	// Step 385: t4 = x^0xea4ce6919c7e9da513d75a5627c38344bcd510d6c9940f5ed48752a49ef938f617216eb1f4028800
	for s := 0; s < 11; s++ {
		t4.Square(t4)
	}

	// Step 386: t3 = x^0xea4ce6919c7e9da513d75a5627c38344bcd510d6c9940f5ed48752a49ef938f617216eb1f4028813
	t3.Mul(t3, t4)

	// Step 393: t3 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a9524f7c9c7b0b90b758fa01440980
	for s := 0; s < 7; s++ {
		t3.Square(t3)
	}

	// Step 394: t2 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a9524f7c9c7b0b90b758fa014409a9
	t2.Mul(t2, t3)

	// Step 400: t2 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63e8051026a40
	for s := 0; s < 6; s++ {
		t2.Square(t2)
	}

	// Step 401: t1 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63e8051026a6d
	t1.Mul(t1, t2)

	// Step 413: t1 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63e8051026a6d000
	for s := 0; s < 12; s++ {
		t1.Square(t1)
	}

	// Step 414: t0 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63e8051026a6d039
	t0.Mul(t0, t1)

	// Step 420: t0 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a9524f7c9c7b0b90b758fa014409a9b40e40
	for s := 0; s < 6; s++ {
		t0.Square(t0)
	}

	// Step 421: t0 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a9524f7c9c7b0b90b758fa014409a9b40e55
	t0.Mul(z, t0)

	// Step 427: t0 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63e8051026a6d039540
	for s := 0; s < 6; s++ {
		t0.Square(t0)
	}

	// Step 428: t0 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63e8051026a6d039555
	t0.Mul(z, t0)

	// Step 434: t0 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a9524f7c9c7b0b90b758fa014409a9b40e55540
	for s := 0; s < 6; s++ {
		t0.Square(t0)
	}

	// Step 435: t0 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a9524f7c9c7b0b90b758fa014409a9b40e55555
	t0.Mul(z, t0)

	// Step 441: t0 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63e8051026a6d039555540
	for s := 0; s < 6; s++ {
		t0.Square(t0)
	}

	// Step 442: t0 = x^0x1d499cd2338fd3b4a27aeb4ac4f87068979aa21ad93281ebda90ea5493df271ec2e42dd63e8051026a6d039555555
	t0.Mul(z, t0)

	// Step 448: t0 = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a9524f7c9c7b0b90b758fa014409a9b40e55555540
	for s := 0; s < 6; s++ {
		t0.Square(t0)
	}

	// Step 449: z = x^0x75267348ce3f4ed289ebad2b13e1c1a25e6a886b64ca07af6a43a9524f7c9c7b0b90b758fa014409a9b40e55555555
	z.Mul(z, t0)

	return z
}
