// Copyright 2020-2025 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package fptower

import (
	"github.com/yelhousni/batch-subgroup-membership/bls12376-strong/fp"
)

// q + r'.r = 1, i.e., qInvNeg = - q⁻¹ mod r
// used for Montgomery reduction
const qInvNeg uint64 = 12533140639073697789

// Field modulus q (Fp)
const (
	q0 uint64 = 1392571182119299755
	q1 uint64 = 17732678817110295176
	q2 uint64 = 6833235323646835000
	q3 uint64 = 4953067958500430863
	q4 uint64 = 11895087823808086915
	q5 uint64 = 65949697719434909
)

var qElement = fp.Element{
	q0,
	q1,
	q2,
	q3,
	q4,
	q5,
}

//go:noescape
func addE2(res, x, y *E2)

//go:noescape
func subE2(res, x, y *E2)

//go:noescape
func doubleE2(res, x *E2)

//go:noescape
func negE2(res, x *E2)
