// Copyright 2020-2025 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package fr

// expBySqrtExp is equivalent to z.Exp(x, 18e69928510ede0708669f83970a54e326771e5922054069e0e0fc9)
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) expBySqrtExp(x Element) *Element {
	// addition chain:
	//
	//	_10       = 2*1
	//	_100      = 2*_10
	//	_101      = 1 + _100
	//	_111      = _10 + _101
	//	_1001     = _10 + _111
	//	_1011     = _10 + _1001
	//	_1101     = _10 + _1011
	//	_1111     = _10 + _1101
	//	_10001    = _10 + _1111
	//	_10101    = _100 + _10001
	//	_10111    = _10 + _10101
	//	_11001    = _10 + _10111
	//	_11011    = _10 + _11001
	//	_11101    = _10 + _11011
	//	_110000   = _10101 + _11011
	//	_111111   = _1111 + _110000
	//	_11000000 = _110000 << 2
	//	_11000111 = _111 + _11000000
	//	i39       = ((_11000111 << 6 + _1101) << 7 + _11001) << 5
	//	i53       = ((_101 + i39) << 7 + _101) << 4 + 1
	//	i70       = 2*((i53 << 9 + _11101) << 5 + _10111)
	//	i87       = ((1 + i70) << 9 + _111) << 5 + 1
	//	i109      = ((i87 << 9 + _11001) << 3 + _101) << 8
	//	i127      = ((_111111 + i109) << 8 + _111) << 7 + _10111
	//	i148      = ((i127 << 7 + _101) << 7 + _10101) << 5
	//	i166      = ((_111 + i148) << 8 + _11001) << 7 + _11001
	//	i181      = ((i166 << 5 + _11011) << 5 + _10001) << 3
	//	i196      = ((_111 + i181) << 6 + _1011) << 6 + _1001
	//	i224      = ((i196 << 4 + 1) << 11 + _10101) << 11
	//	i241      = ((_1101 + i224) << 6 + _1111) << 8 + _111
	//	return      (i241 << 11 + _111111) << 6 + _1001
	//
	// Operations: 213 squares 47 multiplies

	// Allocate Temporaries.
	var (
		t0  = new(Element)
		t1  = new(Element)
		t2  = new(Element)
		t3  = new(Element)
		t4  = new(Element)
		t5  = new(Element)
		t6  = new(Element)
		t7  = new(Element)
		t8  = new(Element)
		t9  = new(Element)
		t10 = new(Element)
		t11 = new(Element)
		t12 = new(Element)
	)

	// var t0,t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12 Element
	// Step 1: t0 = x^0x2
	t0.Square(&x)

	// Step 2: t4 = x^0x4
	t4.Square(t0)

	// Step 3: t9 = x^0x5
	t9.Mul(&x, t4)

	// Step 4: t1 = x^0x7
	t1.Mul(t0, t9)

	// Step 5: z = x^0x9
	z.Mul(t0, t1)

	// Step 6: t5 = x^0xb
	t5.Mul(t0, z)

	// Step 7: t3 = x^0xd
	t3.Mul(t0, t5)

	// Step 8: t2 = x^0xf
	t2.Mul(t0, t3)

	// Step 9: t6 = x^0x11
	t6.Mul(t0, t2)

	// Step 10: t4 = x^0x15
	t4.Mul(t4, t6)

	// Step 11: t10 = x^0x17
	t10.Mul(t0, t4)

	// Step 12: t8 = x^0x19
	t8.Mul(t0, t10)

	// Step 13: t7 = x^0x1b
	t7.Mul(t0, t8)

	// Step 14: t11 = x^0x1d
	t11.Mul(t0, t7)

	// Step 15: t12 = x^0x30
	t12.Mul(t4, t7)

	// Step 16: t0 = x^0x3f
	t0.Mul(t2, t12)

	// Step 18: t12 = x^0xc0
	for s := 0; s < 2; s++ {
		t12.Square(t12)
	}

	// Step 19: t12 = x^0xc7
	t12.Mul(t1, t12)

	// Step 25: t12 = x^0x31c0
	for s := 0; s < 6; s++ {
		t12.Square(t12)
	}

	// Step 26: t12 = x^0x31cd
	t12.Mul(t3, t12)

	// Step 33: t12 = x^0x18e680
	for s := 0; s < 7; s++ {
		t12.Square(t12)
	}

	// Step 34: t12 = x^0x18e699
	t12.Mul(t8, t12)

	// Step 39: t12 = x^0x31cd320
	for s := 0; s < 5; s++ {
		t12.Square(t12)
	}

	// Step 40: t12 = x^0x31cd325
	t12.Mul(t9, t12)

	// Step 47: t12 = x^0x18e699280
	for s := 0; s < 7; s++ {
		t12.Square(t12)
	}

	// Step 48: t12 = x^0x18e699285
	t12.Mul(t9, t12)

	// Step 52: t12 = x^0x18e6992850
	for s := 0; s < 4; s++ {
		t12.Square(t12)
	}

	// Step 53: t12 = x^0x18e6992851
	t12.Mul(&x, t12)

	// Step 62: t12 = x^0x31cd3250a200
	for s := 0; s < 9; s++ {
		t12.Square(t12)
	}

	// Step 63: t11 = x^0x31cd3250a21d
	t11.Mul(t11, t12)

	// Step 68: t11 = x^0x639a64a1443a0
	for s := 0; s < 5; s++ {
		t11.Square(t11)
	}

	// Step 69: t11 = x^0x639a64a1443b7
	t11.Mul(t10, t11)

	// Step 70: t11 = x^0xc734c9428876e
	t11.Square(t11)

	// Step 71: t11 = x^0xc734c9428876f
	t11.Mul(&x, t11)

	// Step 80: t11 = x^0x18e69928510ede00
	for s := 0; s < 9; s++ {
		t11.Square(t11)
	}

	// Step 81: t11 = x^0x18e69928510ede07
	t11.Mul(t1, t11)

	// Step 86: t11 = x^0x31cd3250a21dbc0e0
	for s := 0; s < 5; s++ {
		t11.Square(t11)
	}

	// Step 87: t11 = x^0x31cd3250a21dbc0e1
	t11.Mul(&x, t11)

	// Step 96: t11 = x^0x639a64a1443b781c200
	for s := 0; s < 9; s++ {
		t11.Square(t11)
	}

	// Step 97: t11 = x^0x639a64a1443b781c219
	t11.Mul(t8, t11)

	// Step 100: t11 = x^0x31cd3250a21dbc0e10c8
	for s := 0; s < 3; s++ {
		t11.Square(t11)
	}

	// Step 101: t11 = x^0x31cd3250a21dbc0e10cd
	t11.Mul(t9, t11)

	// Step 109: t11 = x^0x31cd3250a21dbc0e10cd00
	for s := 0; s < 8; s++ {
		t11.Square(t11)
	}

	// Step 110: t11 = x^0x31cd3250a21dbc0e10cd3f
	t11.Mul(t0, t11)

	// Step 118: t11 = x^0x31cd3250a21dbc0e10cd3f00
	for s := 0; s < 8; s++ {
		t11.Square(t11)
	}

	// Step 119: t11 = x^0x31cd3250a21dbc0e10cd3f07
	t11.Mul(t1, t11)

	// Step 126: t11 = x^0x18e69928510ede0708669f8380
	for s := 0; s < 7; s++ {
		t11.Square(t11)
	}

	// Step 127: t10 = x^0x18e69928510ede0708669f8397
	t10.Mul(t10, t11)

	// Step 134: t10 = x^0xc734c9428876f0384334fc1cb80
	for s := 0; s < 7; s++ {
		t10.Square(t10)
	}

	// Step 135: t9 = x^0xc734c9428876f0384334fc1cb85
	t9.Mul(t9, t10)

	// Step 142: t9 = x^0x639a64a1443b781c219a7e0e5c280
	for s := 0; s < 7; s++ {
		t9.Square(t9)
	}

	// Step 143: t9 = x^0x639a64a1443b781c219a7e0e5c295
	t9.Mul(t4, t9)

	// Step 148: t9 = x^0xc734c9428876f0384334fc1cb852a0
	for s := 0; s < 5; s++ {
		t9.Square(t9)
	}

	// Step 149: t9 = x^0xc734c9428876f0384334fc1cb852a7
	t9.Mul(t1, t9)

	// Step 157: t9 = x^0xc734c9428876f0384334fc1cb852a700
	for s := 0; s < 8; s++ {
		t9.Square(t9)
	}

	// Step 158: t9 = x^0xc734c9428876f0384334fc1cb852a719
	t9.Mul(t8, t9)

	// Step 165: t9 = x^0x639a64a1443b781c219a7e0e5c29538c80
	for s := 0; s < 7; s++ {
		t9.Square(t9)
	}

	// Step 166: t8 = x^0x639a64a1443b781c219a7e0e5c29538c99
	t8.Mul(t8, t9)

	// Step 171: t8 = x^0xc734c9428876f0384334fc1cb852a719320
	for s := 0; s < 5; s++ {
		t8.Square(t8)
	}

	// Step 172: t7 = x^0xc734c9428876f0384334fc1cb852a71933b
	t7.Mul(t7, t8)

	// Step 177: t7 = x^0x18e69928510ede0708669f83970a54e326760
	for s := 0; s < 5; s++ {
		t7.Square(t7)
	}

	// Step 178: t6 = x^0x18e69928510ede0708669f83970a54e326771
	t6.Mul(t6, t7)

	// Step 181: t6 = x^0xc734c9428876f0384334fc1cb852a71933b88
	for s := 0; s < 3; s++ {
		t6.Square(t6)
	}

	// Step 182: t6 = x^0xc734c9428876f0384334fc1cb852a71933b8f
	t6.Mul(t1, t6)

	// Step 188: t6 = x^0x31cd3250a21dbc0e10cd3f072e14a9c64cee3c0
	for s := 0; s < 6; s++ {
		t6.Square(t6)
	}

	// Step 189: t5 = x^0x31cd3250a21dbc0e10cd3f072e14a9c64cee3cb
	t5.Mul(t5, t6)

	// Step 195: t5 = x^0xc734c9428876f0384334fc1cb852a71933b8f2c0
	for s := 0; s < 6; s++ {
		t5.Square(t5)
	}

	// Step 196: t5 = x^0xc734c9428876f0384334fc1cb852a71933b8f2c9
	t5.Mul(z, t5)

	// Step 200: t5 = x^0xc734c9428876f0384334fc1cb852a71933b8f2c90
	for s := 0; s < 4; s++ {
		t5.Square(t5)
	}

	// Step 201: t5 = x^0xc734c9428876f0384334fc1cb852a71933b8f2c91
	t5.Mul(&x, t5)

	// Step 212: t5 = x^0x639a64a1443b781c219a7e0e5c29538c99dc79648800
	for s := 0; s < 11; s++ {
		t5.Square(t5)
	}

	// Step 213: t4 = x^0x639a64a1443b781c219a7e0e5c29538c99dc79648815
	t4.Mul(t4, t5)

	// Step 224: t4 = x^0x31cd3250a21dbc0e10cd3f072e14a9c64cee3cb2440a800
	for s := 0; s < 11; s++ {
		t4.Square(t4)
	}

	// Step 225: t3 = x^0x31cd3250a21dbc0e10cd3f072e14a9c64cee3cb2440a80d
	t3.Mul(t3, t4)

	// Step 231: t3 = x^0xc734c9428876f0384334fc1cb852a71933b8f2c9102a0340
	for s := 0; s < 6; s++ {
		t3.Square(t3)
	}

	// Step 232: t2 = x^0xc734c9428876f0384334fc1cb852a71933b8f2c9102a034f
	t2.Mul(t2, t3)

	// Step 240: t2 = x^0xc734c9428876f0384334fc1cb852a71933b8f2c9102a034f00
	for s := 0; s < 8; s++ {
		t2.Square(t2)
	}

	// Step 241: t1 = x^0xc734c9428876f0384334fc1cb852a71933b8f2c9102a034f07
	t1.Mul(t1, t2)

	// Step 252: t1 = x^0x639a64a1443b781c219a7e0e5c29538c99dc7964881501a783800
	for s := 0; s < 11; s++ {
		t1.Square(t1)
	}

	// Step 253: t0 = x^0x639a64a1443b781c219a7e0e5c29538c99dc7964881501a78383f
	t0.Mul(t0, t1)

	// Step 259: t0 = x^0x18e69928510ede0708669f83970a54e326771e5922054069e0e0fc0
	for s := 0; s < 6; s++ {
		t0.Square(t0)
	}

	// Step 260: z = x^0x18e69928510ede0708669f83970a54e326771e5922054069e0e0fc9
	z.Mul(z, t0)

	return z
}

// expByLegendreExp is equivalent to z.Exp(x, 639a64a1443b781c219a7e0e5c29538c99dc7964881501a78383f2600000000)
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) expByLegendreExp(x Element) *Element {
	// addition chain:
	//
	//	_10       = 2*1
	//	_11       = 1 + _10
	//	_101      = _10 + _11
	//	_111      = _10 + _101
	//	_1001     = _10 + _111
	//	_1011     = _10 + _1001
	//	_1101     = _10 + _1011
	//	_1111     = _10 + _1101
	//	_10001    = _10 + _1111
	//	_10011    = _10 + _10001
	//	_10101    = _10 + _10011
	//	_10111    = _10 + _10101
	//	_11001    = _10 + _10111
	//	_11011    = _10 + _11001
	//	_11101    = _10 + _11011
	//	_110000   = _10011 + _11101
	//	_111111   = _1111 + _110000
	//	_11000000 = _110000 << 2
	//	_11000111 = _111 + _11000000
	//	i40       = ((_11000111 << 6 + _1101) << 7 + _11001) << 5
	//	i54       = ((_101 + i40) << 7 + _101) << 4 + 1
	//	i71       = 2*((i54 << 9 + _11101) << 5 + _10111)
	//	i88       = ((1 + i71) << 9 + _111) << 5 + 1
	//	i110      = ((i88 << 9 + _11001) << 3 + _101) << 8
	//	i128      = ((_111111 + i110) << 8 + _111) << 7 + _10111
	//	i149      = ((i128 << 7 + _101) << 7 + _10101) << 5
	//	i167      = ((_111 + i149) << 8 + _11001) << 7 + _11001
	//	i182      = ((i167 << 5 + _11011) << 5 + _10001) << 3
	//	i197      = ((_111 + i182) << 6 + _1011) << 6 + _1001
	//	i225      = ((i197 << 4 + 1) << 11 + _10101) << 11
	//	i242      = ((_1101 + i225) << 6 + _1111) << 8 + _111
	//	return      ((i242 << 11 + _111111) << 7 + _10011) << 33
	//
	// Operations: 246 squares 49 multiplies

	// Allocate Temporaries.
	var (
		t0  = new(Element)
		t1  = new(Element)
		t2  = new(Element)
		t3  = new(Element)
		t4  = new(Element)
		t5  = new(Element)
		t6  = new(Element)
		t7  = new(Element)
		t8  = new(Element)
		t9  = new(Element)
		t10 = new(Element)
		t11 = new(Element)
		t12 = new(Element)
		t13 = new(Element)
	)

	// var t0,t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13 Element
	// Step 1: t0 = x^0x2
	t0.Square(&x)

	// Step 2: z = x^0x3
	z.Mul(&x, t0)

	// Step 3: t10 = x^0x5
	t10.Mul(t0, z)

	// Step 4: t1 = x^0x7
	t1.Mul(t0, t10)

	// Step 5: t5 = x^0x9
	t5.Mul(t0, t1)

	// Step 6: t6 = x^0xb
	t6.Mul(t0, t5)

	// Step 7: t3 = x^0xd
	t3.Mul(t0, t6)

	// Step 8: t2 = x^0xf
	t2.Mul(t0, t3)

	// Step 9: t7 = x^0x11
	t7.Mul(t0, t2)

	// Step 10: z = x^0x13
	z.Mul(t0, t7)

	// Step 11: t4 = x^0x15
	t4.Mul(t0, z)

	// Step 12: t11 = x^0x17
	t11.Mul(t0, t4)

	// Step 13: t9 = x^0x19
	t9.Mul(t0, t11)

	// Step 14: t8 = x^0x1b
	t8.Mul(t0, t9)

	// Step 15: t12 = x^0x1d
	t12.Mul(t0, t8)

	// Step 16: t13 = x^0x30
	t13.Mul(z, t12)

	// Step 17: t0 = x^0x3f
	t0.Mul(t2, t13)

	// Step 19: t13 = x^0xc0
	for s := 0; s < 2; s++ {
		t13.Square(t13)
	}

	// Step 20: t13 = x^0xc7
	t13.Mul(t1, t13)

	// Step 26: t13 = x^0x31c0
	for s := 0; s < 6; s++ {
		t13.Square(t13)
	}

	// Step 27: t13 = x^0x31cd
	t13.Mul(t3, t13)

	// Step 34: t13 = x^0x18e680
	for s := 0; s < 7; s++ {
		t13.Square(t13)
	}

	// Step 35: t13 = x^0x18e699
	t13.Mul(t9, t13)

	// Step 40: t13 = x^0x31cd320
	for s := 0; s < 5; s++ {
		t13.Square(t13)
	}

	// Step 41: t13 = x^0x31cd325
	t13.Mul(t10, t13)

	// Step 48: t13 = x^0x18e699280
	for s := 0; s < 7; s++ {
		t13.Square(t13)
	}

	// Step 49: t13 = x^0x18e699285
	t13.Mul(t10, t13)

	// Step 53: t13 = x^0x18e6992850
	for s := 0; s < 4; s++ {
		t13.Square(t13)
	}

	// Step 54: t13 = x^0x18e6992851
	t13.Mul(&x, t13)

	// Step 63: t13 = x^0x31cd3250a200
	for s := 0; s < 9; s++ {
		t13.Square(t13)
	}

	// Step 64: t12 = x^0x31cd3250a21d
	t12.Mul(t12, t13)

	// Step 69: t12 = x^0x639a64a1443a0
	for s := 0; s < 5; s++ {
		t12.Square(t12)
	}

	// Step 70: t12 = x^0x639a64a1443b7
	t12.Mul(t11, t12)

	// Step 71: t12 = x^0xc734c9428876e
	t12.Square(t12)

	// Step 72: t12 = x^0xc734c9428876f
	t12.Mul(&x, t12)

	// Step 81: t12 = x^0x18e69928510ede00
	for s := 0; s < 9; s++ {
		t12.Square(t12)
	}

	// Step 82: t12 = x^0x18e69928510ede07
	t12.Mul(t1, t12)

	// Step 87: t12 = x^0x31cd3250a21dbc0e0
	for s := 0; s < 5; s++ {
		t12.Square(t12)
	}

	// Step 88: t12 = x^0x31cd3250a21dbc0e1
	t12.Mul(&x, t12)

	// Step 97: t12 = x^0x639a64a1443b781c200
	for s := 0; s < 9; s++ {
		t12.Square(t12)
	}

	// Step 98: t12 = x^0x639a64a1443b781c219
	t12.Mul(t9, t12)

	// Step 101: t12 = x^0x31cd3250a21dbc0e10c8
	for s := 0; s < 3; s++ {
		t12.Square(t12)
	}

	// Step 102: t12 = x^0x31cd3250a21dbc0e10cd
	t12.Mul(t10, t12)

	// Step 110: t12 = x^0x31cd3250a21dbc0e10cd00
	for s := 0; s < 8; s++ {
		t12.Square(t12)
	}

	// Step 111: t12 = x^0x31cd3250a21dbc0e10cd3f
	t12.Mul(t0, t12)

	// Step 119: t12 = x^0x31cd3250a21dbc0e10cd3f00
	for s := 0; s < 8; s++ {
		t12.Square(t12)
	}

	// Step 120: t12 = x^0x31cd3250a21dbc0e10cd3f07
	t12.Mul(t1, t12)

	// Step 127: t12 = x^0x18e69928510ede0708669f8380
	for s := 0; s < 7; s++ {
		t12.Square(t12)
	}

	// Step 128: t11 = x^0x18e69928510ede0708669f8397
	t11.Mul(t11, t12)

	// Step 135: t11 = x^0xc734c9428876f0384334fc1cb80
	for s := 0; s < 7; s++ {
		t11.Square(t11)
	}

	// Step 136: t10 = x^0xc734c9428876f0384334fc1cb85
	t10.Mul(t10, t11)

	// Step 143: t10 = x^0x639a64a1443b781c219a7e0e5c280
	for s := 0; s < 7; s++ {
		t10.Square(t10)
	}

	// Step 144: t10 = x^0x639a64a1443b781c219a7e0e5c295
	t10.Mul(t4, t10)

	// Step 149: t10 = x^0xc734c9428876f0384334fc1cb852a0
	for s := 0; s < 5; s++ {
		t10.Square(t10)
	}

	// Step 150: t10 = x^0xc734c9428876f0384334fc1cb852a7
	t10.Mul(t1, t10)

	// Step 158: t10 = x^0xc734c9428876f0384334fc1cb852a700
	for s := 0; s < 8; s++ {
		t10.Square(t10)
	}

	// Step 159: t10 = x^0xc734c9428876f0384334fc1cb852a719
	t10.Mul(t9, t10)

	// Step 166: t10 = x^0x639a64a1443b781c219a7e0e5c29538c80
	for s := 0; s < 7; s++ {
		t10.Square(t10)
	}

	// Step 167: t9 = x^0x639a64a1443b781c219a7e0e5c29538c99
	t9.Mul(t9, t10)

	// Step 172: t9 = x^0xc734c9428876f0384334fc1cb852a719320
	for s := 0; s < 5; s++ {
		t9.Square(t9)
	}

	// Step 173: t8 = x^0xc734c9428876f0384334fc1cb852a71933b
	t8.Mul(t8, t9)

	// Step 178: t8 = x^0x18e69928510ede0708669f83970a54e326760
	for s := 0; s < 5; s++ {
		t8.Square(t8)
	}

	// Step 179: t7 = x^0x18e69928510ede0708669f83970a54e326771
	t7.Mul(t7, t8)

	// Step 182: t7 = x^0xc734c9428876f0384334fc1cb852a71933b88
	for s := 0; s < 3; s++ {
		t7.Square(t7)
	}

	// Step 183: t7 = x^0xc734c9428876f0384334fc1cb852a71933b8f
	t7.Mul(t1, t7)

	// Step 189: t7 = x^0x31cd3250a21dbc0e10cd3f072e14a9c64cee3c0
	for s := 0; s < 6; s++ {
		t7.Square(t7)
	}

	// Step 190: t6 = x^0x31cd3250a21dbc0e10cd3f072e14a9c64cee3cb
	t6.Mul(t6, t7)

	// Step 196: t6 = x^0xc734c9428876f0384334fc1cb852a71933b8f2c0
	for s := 0; s < 6; s++ {
		t6.Square(t6)
	}

	// Step 197: t5 = x^0xc734c9428876f0384334fc1cb852a71933b8f2c9
	t5.Mul(t5, t6)

	// Step 201: t5 = x^0xc734c9428876f0384334fc1cb852a71933b8f2c90
	for s := 0; s < 4; s++ {
		t5.Square(t5)
	}

	// Step 202: t5 = x^0xc734c9428876f0384334fc1cb852a71933b8f2c91
	t5.Mul(&x, t5)

	// Step 213: t5 = x^0x639a64a1443b781c219a7e0e5c29538c99dc79648800
	for s := 0; s < 11; s++ {
		t5.Square(t5)
	}

	// Step 214: t4 = x^0x639a64a1443b781c219a7e0e5c29538c99dc79648815
	t4.Mul(t4, t5)

	// Step 225: t4 = x^0x31cd3250a21dbc0e10cd3f072e14a9c64cee3cb2440a800
	for s := 0; s < 11; s++ {
		t4.Square(t4)
	}

	// Step 226: t3 = x^0x31cd3250a21dbc0e10cd3f072e14a9c64cee3cb2440a80d
	t3.Mul(t3, t4)

	// Step 232: t3 = x^0xc734c9428876f0384334fc1cb852a71933b8f2c9102a0340
	for s := 0; s < 6; s++ {
		t3.Square(t3)
	}

	// Step 233: t2 = x^0xc734c9428876f0384334fc1cb852a71933b8f2c9102a034f
	t2.Mul(t2, t3)

	// Step 241: t2 = x^0xc734c9428876f0384334fc1cb852a71933b8f2c9102a034f00
	for s := 0; s < 8; s++ {
		t2.Square(t2)
	}

	// Step 242: t1 = x^0xc734c9428876f0384334fc1cb852a71933b8f2c9102a034f07
	t1.Mul(t1, t2)

	// Step 253: t1 = x^0x639a64a1443b781c219a7e0e5c29538c99dc7964881501a783800
	for s := 0; s < 11; s++ {
		t1.Square(t1)
	}

	// Step 254: t0 = x^0x639a64a1443b781c219a7e0e5c29538c99dc7964881501a78383f
	t0.Mul(t0, t1)

	// Step 261: t0 = x^0x31cd3250a21dbc0e10cd3f072e14a9c64cee3cb2440a80d3c1c1f80
	for s := 0; s < 7; s++ {
		t0.Square(t0)
	}

	// Step 262: z = x^0x31cd3250a21dbc0e10cd3f072e14a9c64cee3cb2440a80d3c1c1f93
	z.Mul(z, t0)

	// Step 295: z = x^0x639a64a1443b781c219a7e0e5c29538c99dc7964881501a78383f2600000000
	for s := 0; s < 33; s++ {
		z.Square(z)
	}

	return z
}
